package xmlfluss.apt;

import com.palantir.javapoet.*;
import xmlfluss.codegen.model.*;
import xmlfluss.codegen.model.FieldSpec;
import xmlfluss.codegen.plan.*;
import xmlfluss.path.Predicate;

import javax.annotation.processing.Generated;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDate;
import java.util.*;
import java.util.function.Consumer;

/**
 * Generates the Java source for a {@code ${ClassName}Parser}. Renders both the
 * top-level record and any nested records discovered by the {@link xmlfluss.codegen.classify.CoreClassifier}.
 */
final class Emitter {

    private static final ClassName CN_INPUT_STREAM = ClassName.get(InputStream.class);
    private static final ClassName CN_STREAM = ClassName.get("java.util.stream", "Stream");
    private static final ClassName CN_STREAM_SUPPORT = ClassName.get("java.util.stream", "StreamSupport");
    private static final ClassName CN_SPLITERATOR = ClassName.get("java.util", "Spliterator");
    private static final ClassName CN_ABSTRACT_SPLITERATOR = ClassName.get("java.util.Spliterators", "AbstractSpliterator");
    private static final ClassName CN_CONSUMER = ClassName.get(Consumer.class);
    private static final ClassName CN_LIST = ClassName.get("java.util", "List");
    private static final ClassName CN_ARRAY_LIST = ClassName.get("java.util", "ArrayList");
    private static final ClassName CN_COLLECTIONS = ClassName.get("java.util", "Collections");
    private static final ClassName CN_MAP = ClassName.get("java.util", "Map");
    private static final ClassName CN_LINKED_HASH_MAP = ClassName.get("java.util", "LinkedHashMap");
    private static final ClassName CN_OBJECTS = ClassName.get("java.util", "Objects");

    private static final ClassName CN_CURSOR = ClassName.get("xmlfluss.runtime", "XmlReadCursor");
    private static final ClassName CN_PATHS = ClassName.get("xmlfluss.runtime", "Paths");
    private static final ClassName CN_COMPILED_PATH = ClassName.get("xmlfluss.path", "CompiledPath");
    private static final ClassName CN_LOCATION = ClassName.get("xmlfluss", "Location");
    private static final ClassName CN_MISSING_EX = ClassName.get("xmlfluss", "XmlParseException", "Missing");
    private static final ClassName CN_COERCIONS = ClassName.get("xmlfluss.runtime", "Coercions");
    private static final ClassName CN_ADAPTER = ClassName.get("xmlfluss.runtime", "JavaCursorAdapter");
    public static final String SKIP_CHILD = "c.skipChild()";
    public static final String RETURN_TRUE = "return true";

    private final ProcessingEnvironment env;

    Emitter(ProcessingEnvironment env) {
        this.env = env;
    }

    void emit(RecordSpec topLevel, DispatchPlan plan, NestedRegistry registry) {
        TypeElement origin = Objects.requireNonNull((TypeElement) topLevel.originatingHandle(),
                "originating TypeElement missing for " + topLevel.simpleName());
        ClassName recordType = ClassName.get(origin);
        String parserName = topLevel.simpleName() + "Parser";

        TypeSpec.Builder cls = TypeSpec.classBuilder(parserName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addAnnotation(AnnotationSpec.builder(Generated.class)
                        .addMember("value", "$S", "xml-fluss-apt")
                        .addMember("date", "$S", LocalDate.now().toString())
                        .build())
                .addJavadoc("Generated by xml-fluss-apt — do not edit\n");

        cls.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE)
                .build());

        // Static `Map<String,String> NS` initializer mirroring @XmlNs declarations on the record.
        cls.addField(buildNsField(topLevel.nsMap()));

        cls.addField(com.palantir.javapoet.FieldSpec.builder(CN_COMPILED_PATH, "PATH", Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                .initializer("$T.INSTANCE.compile($S, NS)",
                        CN_PATHS, topLevel.recordPath())
                .build());

        // Walk every field (top-level + nested) and intern each unique @XmlConverter class as a static singleton field.
        Map<String, ConverterRef> converterRefs = collectConverters(topLevel, registry);
        for (ConverterRef ref : converterRefs.values()) {
            cls.addField(com.palantir.javapoet.FieldSpec.builder(ref.cls, ref.varName,
                            Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                    .initializer("new $T()", ref.cls)
                    .build());
        }

        TypeName streamOfRecord = ParameterizedTypeName.get(CN_STREAM, recordType);

        cls.addMethod(MethodSpec.methodBuilder("parse")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addParameter(CN_INPUT_STREAM, "input")
                .returns(streamOfRecord)
                .addStatement("return parse(input, false)")
                .build());

        MethodSpec.Builder parse = MethodSpec.methodBuilder("parse")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addParameter(CN_INPUT_STREAM, "input")
                .addParameter(TypeName.BOOLEAN, "ignoreNamespace")
                .returns(streamOfRecord);
        // Generate the public `parse(InputStream, boolean)` body: open Stax cursor, mount PATH, drive a Spliterator that yields one record per match.
        emitParseBody(parse, recordType);
        cls.addMethod(parse.build());

        MethodSpec.Builder buildOne = MethodSpec.methodBuilder("__buildRecord")
                .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
                .addParameter(CN_CURSOR, "c")
                .returns(recordType);
        // Generate per-field state, the forEachSubrecordChild dispatch over @XmlAttr/@XmlChild/@XmlText/@XmlMap, and the canonical-ctor invocation that returns the record instance.
        buildOne.addCode(buildInstanceBody(recordType, topLevel.fields(), plan, registry,
                converterRefs, /*record=*/true));
        cls.addMethod(buildOne.build());

        for (var entry : registry.byFq().entrySet()) {
            String fq = entry.getKey();
            RecordSpec spec = entry.getValue();
            String helper = registry.helperName(fq);
            TypeElement nestedOrigin = Objects.requireNonNull((TypeElement) spec.originatingHandle(),
                    "originating TypeElement missing for nested " + fq);
            ClassName nestedType = ClassName.get(nestedOrigin);
            DispatchPlan nestedPlan = plan.byFq().get(fq);
            if (nestedPlan == null) {
                throw new IllegalStateException("DispatchPlan missing for nested record " + fq);
            }
            MethodSpec.Builder helperMethod = MethodSpec.methodBuilder(helper)
                    .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
                    .addParameter(CN_CURSOR, "c")
                    .returns(nestedType);
            // Emit a private static helper for each nested record type — same field/dispatch shape as __buildRecord but reused from parent fields that descend into this nested type.
            helperMethod.addCode(buildInstanceBody(nestedType, spec.fields(), nestedPlan, registry,
                    converterRefs, /*record=*/false));
            cls.addMethod(helperMethod.build());
        }

        JavaFile file = JavaFile.builder(topLevel.packageName(), cls.build())
                .skipJavaLangImports(true)
                .build();
        try {
            // Hand the assembled JavaFile to the annotation-processing Filer; this is what creates the .java in the generated-sources dir.
            file.writeTo(env.getFiler());
        } catch (IOException ioe) {
            env.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "xml-fluss-apt: failed to write " + parserName + ": " + ioe.getMessage(),
                    origin);
        }
    }

    private com.palantir.javapoet.FieldSpec buildNsField(Map<String, String> nsMap) {
        TypeName mapType = ParameterizedTypeName.get(CN_MAP,
                ClassName.get("java.lang", "String"),
                ClassName.get("java.lang", "String"));
        com.palantir.javapoet.FieldSpec.Builder b = com.palantir.javapoet.FieldSpec.builder(mapType, "NS",
                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL);
        if (nsMap.isEmpty()) {
            b.initializer("$T.<$T,$T>emptyMap()", CN_COLLECTIONS,
                    ClassName.get(String.class), ClassName.get(String.class));
        } else if (nsMap.size() <= 10) {
            CodeBlock.Builder cb = CodeBlock.builder().add("$T.of(", CN_MAP);
            boolean first = true;
            for (var e : nsMap.entrySet()) {
                if (!first) cb.add(", ");
                first = false;
                cb.add("$S, $S", e.getKey(), e.getValue());
            }
            cb.add(")");
            b.initializer(cb.build());
        } else {
            CodeBlock.Builder cb = CodeBlock.builder()
                    .add("new $T<$T,$T>() {{", CN_LINKED_HASH_MAP,
                            ClassName.get(String.class), ClassName.get(String.class));
            for (var e : nsMap.entrySet()) {
                cb.add("\nput($S, $S);", e.getKey(), e.getValue());
            }
            cb.add("\n}}");
            b.initializer(cb.build());
        }
        return b.build();
    }

    private record ConverterRef(ClassName cls, String varName) {
    }

    private Map<String, ConverterRef> collectConverters(RecordSpec topLevel,
                                                        NestedRegistry registry) {
        Map<String, ConverterRef> out = new LinkedHashMap<>();
        for (FieldSpec f : topLevel.fields()) registerConverter(out, f);
        for (RecordSpec n : registry.byFq().values()) {
            for (FieldSpec f : n.fields()) registerConverter(out, f);
        }
        return out;
    }

    private void registerConverter(Map<String, ConverterRef> sink, FieldSpec f) {
        if (f.coerce() instanceof Coerce.Custom c && !sink.containsKey(c.converterFq())) {
            String varName = "__conv_" + sink.size();
            sink.put(c.converterFq(), new ConverterRef(TypeRefs.toClassName(c.converterClass()), varName));
        }

        if (f.mapKeyField() != null) registerConverter(sink, f.mapKeyField());
        if (f.mapValueField() != null) registerConverter(sink, f.mapValueField());
    }

    private void emitParseBody(MethodSpec.Builder b, ClassName recordType) {
        TypeName spliteratorOfRec = ParameterizedTypeName.get(CN_SPLITERATOR, recordType);
        TypeName abstractSplOfRec = ParameterizedTypeName.get(CN_ABSTRACT_SPLITERATOR, recordType);
        TypeName streamOfRec = ParameterizedTypeName.get(CN_STREAM, recordType);
        TypeName consumerSuperRec = ParameterizedTypeName.get(CN_CONSUMER,
                WildcardTypeName.supertypeOf(recordType));

        TypeSpec spliteratorImpl = TypeSpec.anonymousClassBuilder(
                        "$T.MAX_VALUE, $T.ORDERED | $T.NONNULL",
                        ClassName.get("java.lang", "Long"), CN_SPLITERATOR, CN_SPLITERATOR)
                .superclass(abstractSplOfRec)
                .addMethod(MethodSpec.methodBuilder("tryAdvance")
                        .addAnnotation(Override.class)
                        .addModifiers(Modifier.PUBLIC)
                        .returns(TypeName.BOOLEAN)
                        .addParameter(ParameterSpec.builder(consumerSuperRec, "action").build())
                        .addStatement("if (!cursor.findNextRecord()) return false")
                        .addStatement("action.accept(__buildRecord(cursor))")
                        .addStatement(RETURN_TRUE)
                        .build())
                .build();

        b.addStatement("final $T cursor = new $T(input, PATH, ignoreNamespace)", CN_CURSOR, CN_CURSOR);
        b.beginControlFlow("try");
        b.addStatement("$T splr = $L", spliteratorOfRec, spliteratorImpl);
        b.addStatement("$T stream = $T.stream(splr, false)", streamOfRec, CN_STREAM_SUPPORT);
        b.addStatement("return stream.onClose(cursor::close)");
        b.endControlFlow();
        b.beginControlFlow("catch ($T t)", ClassName.get("java.lang", "Throwable"));
        b.beginControlFlow("try");
        b.addStatement("cursor.close()");
        b.endControlFlow();
        b.beginControlFlow("catch ($T ignored)", ClassName.get("java.lang", "Throwable"));
        b.endControlFlow();
        b.addStatement("throw t");
        b.endControlFlow();
    }

    private CodeBlock buildInstanceBody(ClassName type,
                                        List<FieldSpec> fields,
                                        DispatchPlan plan,
                                        NestedRegistry registry,
                                        Map<String, ConverterRef> converterRefs,
                                        boolean record) {
        String attrFn = record ? "recordAttr" : "childAttr";
        String forEachFn = record ? "forEachRecordChild" : "forEachSubrecordChild";
        String textFn = record ? "recordText" : "subrecordText";
        String locFn = record ? "recordLocation" : "childLocation";

        CodeBlock.Builder cb = CodeBlock.builder();
        cb.addStatement("final $T __loc = c.$L()", CN_LOCATION, locFn);

        // Read attributes immediately.
        for (FieldSpec f : fields) {
            if (!(f.source() instanceof Source.Attr a)) continue;
            cb.addStatement("final $T __raw_$L = c.$L($L, $S)",
                    ClassName.get(String.class), f.name(), attrFn, nsLiteral(a.ns()), a.name());
        }

        FieldSpec textField = null;
        boolean hasChildOrText = false;
        for (FieldSpec f : fields) {
            if (f.source() instanceof Source.Text) {
                textField = f;
                hasChildOrText = true;
                continue;
            }
            if (f.source() instanceof Source.Child
                    || f.source() instanceof Source.PolyChild) {
                hasChildOrText = true;
                emitFieldStateInit(cb, f);
            } else if (f.source() instanceof Source.MapEntry) {
                hasChildOrText = true;
                emitMapStateInit(cb, f);
            }
        }

        if (hasChildOrText) {
            // Counter slots must be declared OUTSIDE the per-sibling lambda so that ++__cnt[0]
            // accumulates across siblings rather than resetting per iteration.
            declareSlotsCode(cb, plan.slots());
            cb.beginControlFlow("$T.$L(c, (ln, ns) ->", CN_ADAPTER, forEachFn);
            emitTopLevelChildSwitch(cb, plan, registry, converterRefs);
            cb.endControlFlow(")");

            if (textField != null) {
                boolean preserve = ((Source.Text) textField.source()).preserveWhitespace();
                cb.addStatement("final $T __raw_$L = c.$L($L)",
                        ClassName.get(String.class), textField.name(), textFn, preserve);
            }
        }

        // Coerce per field, build constructor args.
        List<String> ctorArgs = new ArrayList<>();
        for (FieldSpec f : fields) {
            ctorArgs.add("__final_" + f.name());
            cb.add(coerceField(f, converterRefs));
        }

        StringBuilder args = new StringBuilder();
        for (int i = 0; i < ctorArgs.size(); i++) {
            if (i > 0) args.append(", ");
            args.append(ctorArgs.get(i));
        }
        cb.addStatement("return new $T($L)", type, args.toString());
        return cb.build();
    }

    /**
     * Emit per-field state holders.
     */
    private void emitFieldStateInit(CodeBlock.Builder cb, FieldSpec f) {
        if (f.source() instanceof Source.Text) return;
        if (f.coerce() instanceof Coerce.Nested) {
            TypeName elemBox = TypeRefs.toTypeName(f.elemType()).box();
            if (f.isList()) {
                cb.addStatement("final $T<$T> __list_$L = new $T<>()",
                        CN_LIST, elemBox, f.name(), CN_ARRAY_LIST);
            } else {
                cb.addStatement("final $T[] __nested_$L = new $T[1]",
                        elemBox, f.name(), elemBox);
                cb.addStatement("final boolean[] __set_$L = new boolean[1]", f.name());
            }
        } else if (f.isList()) {
            cb.addStatement("final $T<$T> __list_$L = new $T<>()",
                    CN_LIST, ClassName.get(String.class), f.name(), CN_ARRAY_LIST);
        } else {
            cb.addStatement("final $T[] __raw_$L = new $T[1]",
                    ClassName.get(String.class), f.name(), ClassName.get(String.class));
            cb.addStatement("final $T[] __loc_$L = new $T[1]", CN_LOCATION, f.name(), CN_LOCATION);
            cb.addStatement("final boolean[] __set_$L = new boolean[1]", f.name());
        }
    }

    private void emitMapStateInit(CodeBlock.Builder cb, FieldSpec f) {
        FieldSpec keyF = Objects.requireNonNull(f.mapKeyField(),
                "MapEntry field missing key sub-spec: " + f.name());
        FieldSpec valF = Objects.requireNonNull(f.mapValueField(),
                "MapEntry field missing value sub-spec: " + f.name());
        TypeName keyT = TypeRefs.toTypeName(keyF.fieldType()).box();
        TypeName valStored = valF.isList()
                ? ParameterizedTypeName.get(CN_LIST, TypeRefs.toTypeName(valF.elemType()).box())
                : TypeRefs.toTypeName(valF.fieldType()).box();
        TypeName mapT = ParameterizedTypeName.get(CN_LINKED_HASH_MAP, keyT, valStored);
        cb.addStatement("final $T __map_$L = new $T<>()", mapT, f.name(), CN_LINKED_HASH_MAP);
        if (!f.required()) {
            cb.addStatement("final boolean[] __set_$L = new boolean[1]", f.name());
        }
    }

    /**
     * Bundled inputs to {@link #emitChildSwitchCore}. Built either from a full {@link DispatchPlan}
     * (record/nested bodies) or a {@link MapPlan} (map entries — no map-of-map or polymorphic).
     */
    private record ChildSwitchInputs(
            TrieNode directRoot,
            SlotTable slots,
            Map<QKey, List<DescendantBranch>> byHead,
            Map<QKey, TailTrie> tailTries,
            Map<FieldSpec, MapPlan> mapPlans,
            List<FieldSpec> polyFields,
            String lnVar, String nsVar) {
        static ChildSwitchInputs from(DispatchPlan plan, String lnVar, String nsVar) {
            return new ChildSwitchInputs(plan.directRoot(), plan.slots(),
                    plan.descendantByHead(), plan.tailTries(),
                    plan.mapPlans(), plan.polyFields(), lnVar, nsVar);
        }
        static ChildSwitchInputs from(MapPlan mp, String lnVar, String nsVar) {
            return new ChildSwitchInputs(mp.directRoot(), mp.slots(),
                    mp.descendantByHead(), mp.tailTries(),
                    Collections.emptyMap(), Collections.emptyList(), lnVar, nsVar);
        }
    }

    /**
     * Top-level child dispatch switch shared between record and nested helpers.
     */
    private void emitTopLevelChildSwitch(CodeBlock.Builder cb, DispatchPlan plan,
                                         NestedRegistry registry,
                                         Map<String, ConverterRef> converterRefs) {
        emitChildSwitchCore(cb, ChildSwitchInputs.from(plan, "ln", "ns"), registry, converterRefs);
    }

    /**
     * Opens one arm of an {@code if/else if (...) { ... }} chain over qname matches. Caller is
     * responsible for closing the chain with {@link CodeBlock.Builder#endControlFlow()} (or with a
     * trailing {@code nextControlFlow("else")} + body + {@code endControlFlow()}). Returns the
     * updated {@code first} flag (always {@code false}) so callers can chain further arms.
     */
    private boolean emitQNameArm(CodeBlock.Builder cb, boolean first,
                                 String local, String ns,
                                 String lnVar, String nsVar,
                                 Runnable body) {
        String fmt = "$S.equals($L) && $L";
        if (first) {
            cb.beginControlFlow("if (" + fmt + ")", local, lnVar, nsMatchExprVar(ns, nsVar));
        } else {
            cb.nextControlFlow("else if (" + fmt + ")", local, lnVar, nsMatchExprVar(ns, nsVar));
        }
        body.run();
        return false;
    }

    /**
     * Core child-dispatch switch. Used both by record/nested-record bodies (via the full
     * {@link DispatchPlan}) and by {@code @XmlMap} entries (which only carry direct-child +
     * descendant data — no map-of-map or polymorphic dispatch).
     */
    private void emitChildSwitchCore(CodeBlock.Builder cb, ChildSwitchInputs in,
                                     NestedRegistry registry,
                                     Map<String, ConverterRef> converterRefs) {
        if (in.directRoot.children().isEmpty() && in.byHead.isEmpty()
                && in.mapPlans.isEmpty() && in.polyFields.isEmpty()) {
            cb.addStatement(SKIP_CHILD);
            return;
        }

        // Direct children, grouped by base QKey (predicate variants dispatched inside).
        boolean first = emitGroupedChildArms(cb, in.directRoot.groupChildrenByQKey(), true,
                in.slots, registry, converterRefs, in.lnVar, in.nsVar);
        // Map entry arms.
        for (var me : in.mapPlans.entrySet()) {
            FieldSpec mf = me.getKey();
            MapPlan mp = me.getValue();
            Source.MapEntry mm = (Source.MapEntry) mf.source();
            first = emitQNameArm(cb, first, mm.entryLocal(), mm.entryNs(), in.lnVar, in.nsVar,
                    () -> emitMapEntryCase(cb, mf, mp, registry, converterRefs));
        }
        // Polymorphic arms.
        for (FieldSpec pf : in.polyFields) {
            PolyDispatch d = ((Source.PolyChild) pf.source()).dispatch();
            if (d instanceof PolyDispatch.Tag tag) {
                for (TagVariant v : tag.variants()) {
                    first = emitQNameArm(cb, first, v.local(), v.ns(), in.lnVar, in.nsVar,
                            () -> emitPolyAssign(cb, pf, v.subtypeFq(), registry));
                }
            } else if (d instanceof PolyDispatch.Attr ad) {
                first = emitQNameArm(cb, first, ad.wrapLocal(), ad.wrapNs(), in.lnVar, in.nsVar,
                        () -> emitPolyAttrSwitch(cb, pf, ad, registry));
            }
        }
        // Descendant heads as direct matches.
        for (var entry : in.byHead.entrySet()) {
            QKey head = entry.getKey();
            List<DescendantBranch> branches = entry.getValue();
            first = emitQNameArm(cb, first, head.local(), head.ns(), in.lnVar, in.nsVar,
                    () -> emitDescendantArm(cb, head, branches, in.tailTries, registry, converterRefs, /*terminating=*/false));
        }
        // Else: descendant scan or skipChild.
        if (in.byHead.isEmpty()) {
            if (first) {
                cb.addStatement(SKIP_CHILD);
            } else {
                cb.nextControlFlow("else");
                cb.addStatement(SKIP_CHILD);
                cb.endControlFlow();
            }
        } else {
            cb.nextControlFlow("else");
            cb.beginControlFlow("$T.forEachDescendantInChild(c, (dln, dns) ->", CN_ADAPTER);
            boolean dfirst = true;
            for (var entry : in.byHead.entrySet()) {
                QKey head = entry.getKey();
                List<DescendantBranch> branches = entry.getValue();
                dfirst = emitQNameArm(cb, dfirst, head.local(), head.ns(), "dln", "dns",
                        () -> emitDescendantArm(cb, head, branches, in.tailTries, registry, converterRefs, /*terminating=*/true));
            }
            cb.endControlFlow();
            cb.addStatement("return false");
            cb.endControlFlow(")");
            cb.endControlFlow();
        }
    }

    /**
     * One arm of the descendant dispatch — head matched, walk tail or read leaf.
     */
    @SuppressWarnings("StatementWithEmptyBody")
    private void emitDescendantArm(CodeBlock.Builder cb,
                                   QKey head,
                                   List<DescendantBranch> branches,
                                   Map<QKey, TailTrie> tailTries,
                                   NestedRegistry registry,
                                   Map<String, ConverterRef> converterRefs,
                                   boolean terminating) {
        // The descendant-axis head segment cannot carry a positional predicate (rejected by
        // validateChildPredicate), so brackets here are guaranteed Index-free. We can still have
        // attribute-equality predicates that select among descendant heads.
        List<FieldSpec> unguarded = new ArrayList<>();
        List<DescendantBranch> guarded = new ArrayList<>();
        for (DescendantBranch entry : branches) {
            if (entry.brackets().isEmpty()) unguarded.add(entry.field());
            else guarded.add(entry);
        }
        TailTrie tail = tailTries.get(head);
        if (guarded.isEmpty()) {
            emitDescendantArmBody(cb, head, unguarded, tail, registry, converterRefs);
            if (terminating) cb.addStatement(RETURN_TRUE);
            return;
        }
        boolean first = true;
        for (DescendantBranch entry : guarded) {
            CodeBlock cond = predicateExpr(entry.brackets(), head, new SlotTable());
            if (first) cb.beginControlFlow("if ($L)", cond);
            else cb.nextControlFlow("else if ($L)", cond);
            first = false;
            emitDescendantArmBody(cb, head, List.of(entry.field()), tail, registry, converterRefs);
            if (terminating) cb.addStatement(RETURN_TRUE);
        }
        if (!unguarded.isEmpty()) {
            cb.nextControlFlow("else");
            emitDescendantArmBody(cb, head, unguarded, tail, registry, converterRefs);
            if (terminating) cb.addStatement(RETURN_TRUE);
        }
        cb.endControlFlow();
    }

    private void emitDescendantArmBody(CodeBlock.Builder cb,
                                       QKey head,
                                       List<FieldSpec> headFields,
                                       TailTrie tail,
                                       NestedRegistry registry,
                                       Map<String, ConverterRef> converterRefs) {
        boolean anyEmpty = headFields.stream()
                .anyMatch(f -> ((Source.Child) f.source()).segments().size() == 1);
        boolean anyNonEmpty = headFields.stream()
                .anyMatch(f -> ((Source.Child) f.source()).segments().size() > 1);
        if (anyEmpty && anyNonEmpty) {
            cb.add("// invalid mix — caught at validateChildPaths\n");
        }
        if (anyEmpty) {
            // Single field consuming the head element directly.
            emitLeafReadInline(cb, headFields.get(0), registry);
        } else {
            // Tail trie: pre-built by DispatchPlanBuilder for this head.
            if (tail == null) {
                throw new IllegalStateException("missing tail trie for descendant head " + head);
            }
            emitChildBody(cb, tail.trie(), registry, converterRefs);
        }
    }

    /**
     * Read a single leaf (head=field) inline at descendant matching site.
     */
    private void emitLeafReadInline(CodeBlock.Builder cb, FieldSpec f,
                                    NestedRegistry registry) {
        if (f.coerce() instanceof Coerce.Nested n) {
            String helper = registry.helperName(n.typeFq());
            if (f.isList()) {
                cb.addStatement("__list_$L.add($L(c))", f.name(), helper);
            } else {
                cb.addStatement("__nested_$L[0] = $L(c)", f.name(), helper);
                cb.addStatement("__set_$L[0] = true", f.name());
            }
        } else {
            if (f.isList()) {
                cb.addStatement("__list_$L.add(c.childText(false))", f.name());
            } else {
                cb.addStatement("__loc_$L[0] = c.childLocation()", f.name());
                cb.addStatement("__raw_$L[0] = c.childText(false)", f.name());
                cb.addStatement("__set_$L[0] = true", f.name());
            }
        }
    }

    /**
     * Walk a trie at a non-root node — at the cursor's current child element.
     */
    private void emitChildBody(CodeBlock.Builder cb, TrieNode node,
                               NestedRegistry registry,
                               Map<String, ConverterRef> converterRefs) {
        emitAttrEntries(cb, node);
        emitChildBodyContent(cb, node, registry, converterRefs);
    }

    /**
     * Pure attr reads — safe to run multiple times for overlapping predicate variants.
     */
    private void emitAttrEntries(CodeBlock.Builder cb, TrieNode node) {
        for (AttrEntry ae : node.attrEntries()) {
            FieldSpec f = ae.field();
            cb.beginControlFlow("");
            cb.addStatement("$T __a = c.childAttr($L, $S)",
                    ClassName.get(String.class), nsLiteral(ae.ns()), ae.name());
            cb.beginControlFlow("if (__a != null)");
            if (f.isList()) {
                cb.addStatement("__list_$L.add(__a)", f.name());
            } else {
                cb.addStatement("__raw_$L[0] = __a", f.name());
                cb.addStatement("__loc_$L[0] = c.childLocation()", f.name());
                cb.addStatement("__set_$L[0] = true", f.name());
            }
            cb.endControlFlow();
            cb.endControlFlow();
        }
    }

    /**
     * Per-emitter counter for nested lambda variable names — Java forbids shadowing.
     */
    private int lambdaDepth = 0;

    /**
     * Body-consuming dispatch — text / nested / descend. Caller decides whether to gate it.
     */
    @SuppressWarnings("StatementWithEmptyBody")
    private void emitChildBodyContent(CodeBlock.Builder cb, TrieNode node,
                                      NestedRegistry registry,
                                      Map<String, ConverterRef> converterRefs) {
        boolean hasText = !node.textEntries().isEmpty();
        boolean hasNested = !node.nestedEntries().isEmpty();
        boolean hasDescend = !node.children().isEmpty();
        if (hasNested) {
            for (FieldSpec f : node.nestedEntries()) {
                String helper = registry.helperName(((Coerce.Nested) f.coerce()).typeFq());
                if (f.isList()) {
                    cb.addStatement("__list_$L.add($L(c))", f.name(), helper);
                } else {
                    cb.addStatement("__nested_$L[0] = $L(c)", f.name(), helper);
                    cb.addStatement("__set_$L[0] = true", f.name());
                }
            }
        } else if (hasText) {
            cb.addStatement("$T __t_loc = c.childLocation()", CN_LOCATION);
            cb.addStatement("$T __t = c.childText(false)", ClassName.get(String.class));
            for (FieldSpec f : node.textEntries()) {
                if (f.isList()) {
                    cb.addStatement("__list_$L.add(__t)", f.name());
                } else {
                    cb.addStatement("__raw_$L[0] = __t", f.name());
                    cb.addStatement("__loc_$L[0] = __t_loc", f.name());
                    cb.addStatement("__set_$L[0] = true", f.name());
                }
            }
        } else if (hasDescend) {
            // Lambda var names suffixed by depth — Java forbids shadowing nested lambda
            // params, so each `forEachChild` callback needs unique cln/cns identifiers.
            int depth = ++lambdaDepth;
            String lnVar = depth == 1 ? "cln" : "cln" + depth;
            String nsVar = depth == 1 ? "cns" : "cns" + depth;
            // Counter slots for direct edges under `node` must outlive the per-sibling lambda
            // — declare them here, BEFORE entering forEachChild, so increments accumulate
            // across siblings of the same parent.
            SlotTable slots = node.allocateSlots();
            declareSlotsCode(cb, slots);
            cb.beginControlFlow("$T.forEachChild(c, ($L, $L) ->", CN_ADAPTER, lnVar, nsVar);
            emitChildrenSwitch(cb, node, slots, registry, converterRefs, lnVar, nsVar);
            cb.endControlFlow(")");
            lambdaDepth--;
        } else {
            // node has only attrs, no element drains needed; cursor already positioned at the element.
            // Element body untouched: forEach* call site will skip leftovers.
        }
    }

    private void emitChildrenSwitch(CodeBlock.Builder cb, TrieNode node,
                                    SlotTable slots,
                                    NestedRegistry registry,
                                    Map<String, ConverterRef> converterRefs,
                                    String lnVar, String nsVar) {
        if (node.children().isEmpty()) {
            cb.addStatement(SKIP_CHILD);
            return;
        }
        emitGroupedChildArms(cb, node.groupChildrenByQKey(), true,
                slots, registry, converterRefs, lnVar, nsVar);
        cb.nextControlFlow("else");
        cb.addStatement(SKIP_CHILD);
        cb.endControlFlow();
    }

    private void emitPolyAssign(CodeBlock.Builder cb, FieldSpec f, String subtypeFq,
                                NestedRegistry registry) {
        String helper = registry.helperName(subtypeFq);
        if (f.isList()) {
            cb.addStatement("__list_$L.add($L(c))", f.name(), helper);
        } else {
            cb.addStatement("__nested_$L[0] = $L(c)", f.name(), helper);
            cb.addStatement("__set_$L[0] = true", f.name());
        }
    }

    private void emitPolyAttrSwitch(CodeBlock.Builder cb, FieldSpec f,
                                    PolyDispatch.Attr d, NestedRegistry registry) {
        cb.addStatement("$T __disc_$L = c.childAttr($L, $S)",
                ClassName.get(String.class), f.name(), nsLiteral(d.attrNs()), d.attrLocal());
        boolean first = true;
        for (AttrVariant v : d.variants()) {
            if (first) {
                cb.beginControlFlow("if ($T.equals(__disc_$L, $S))", CN_OBJECTS, f.name(), v.value());
            } else {
                cb.nextControlFlow("else if ($T.equals(__disc_$L, $S))", CN_OBJECTS, f.name(), v.value());
            }
            first = false;
            emitPolyAssign(cb, f, v.subtypeFq(), registry);
        }
        cb.nextControlFlow("else");
        cb.addStatement(SKIP_CHILD);
        cb.endControlFlow();
    }

    /**
     * Build map entry: read key + value via synthetic specs, then store in __map_X.
     */
    private void emitMapEntryCase(CodeBlock.Builder cb, FieldSpec f,
                                  MapPlan mp,
                                  NestedRegistry registry,
                                  Map<String, ConverterRef> converterRefs) {
        FieldSpec keyF = Objects.requireNonNull(f.mapKeyField(),
                "MapEntry field missing key sub-spec: " + f.name());
        FieldSpec valF = Objects.requireNonNull(f.mapValueField(),
                "MapEntry field missing value sub-spec: " + f.name());
        List<FieldSpec> mapSubFields = List.of(keyF, valF);
        for (FieldSpec sf : mapSubFields) {
            if (sf.source() instanceof Source.Attr a) {
                if (sf.isList()) {
                    cb.addStatement("final $T<$T> __list_$L = new $T<>()",
                            CN_LIST, ClassName.get(String.class), sf.name(), CN_ARRAY_LIST);
                    cb.beginControlFlow("");
                    cb.addStatement("$T __a = c.childAttr($L, $S)",
                            ClassName.get(String.class), nsLiteral(a.ns()), a.name());
                    cb.beginControlFlow("if (__a != null)");
                    cb.addStatement("__list_$L.add(__a)", sf.name());
                    cb.endControlFlow();
                    cb.endControlFlow();
                } else {
                    cb.addStatement("final $T __raw_$L = c.childAttr($L, $S)",
                            ClassName.get(String.class), sf.name(), nsLiteral(a.ns()), a.name());
                }
            } else {
                emitFieldStateInit(cb, sf);
            }
        }
        if (!mp.directRoot().isEmpty() || !mp.descendantByHead().isEmpty()) {
            declareSlotsCode(cb, mp.slots());
            cb.beginControlFlow("$T.forEachSubrecordChild(c, (mln, mns) ->", CN_ADAPTER);
            emitMapEntrySwitch(cb, mp, registry, converterRefs);
            cb.endControlFlow(")");
        }
        // Coerce key + value, store.
        cb.add(coerceField(keyF, converterRefs));
        cb.add(coerceField(valF, converterRefs));
        if (valF.isList()) {
            cb.addStatement("__map_$L.computeIfAbsent(__final_$L, __k -> new $T<>()).addAll(__final_$L)",
                    f.name(), keyF.name(), CN_ARRAY_LIST, valF.name());
        } else {
            cb.addStatement("__map_$L.put(__final_$L, __final_$L)", f.name(), keyF.name(), valF.name());
        }
        if (!f.required()) {
            cb.addStatement("__set_$L[0] = true", f.name());
        }
    }

    /**
     * Map-entry child dispatch: pure plan walker over the pre-built {@link MapPlan}.
     * MapPlan has no map-of-map or polymorphic children.
     */
    private void emitMapEntrySwitch(CodeBlock.Builder cb, MapPlan mp,
                                    NestedRegistry registry,
                                    Map<String, ConverterRef> converterRefs) {
        emitChildSwitchCore(cb, ChildSwitchInputs.from(mp, "mln", "mns"), registry, converterRefs);
    }

    /**
     * Emits {@code final T __final_name = ...;} for one field.
     */
    private CodeBlock coerceField(FieldSpec f,
                                  Map<String, ConverterRef> converterRefs) {
        CodeBlock.Builder cb = CodeBlock.builder();
        TypeName declared = TypeRefs.toTypeName(f.fieldType());

        if (f.coerce() instanceof Coerce.MapAggregate) {
            if (f.required()) {
                cb.addStatement("final $T __final_$L = $T.unmodifiableMap(__map_$L)",
                        declared, f.name(), CN_COLLECTIONS, f.name());
            } else {
                cb.addStatement("final $T __final_$L = (!__set_$L[0]) ? null : $T.unmodifiableMap(__map_$L)",
                        declared, f.name(), f.name(), CN_COLLECTIONS, f.name());
            }
            return cb.build();
        }

        if (f.source() instanceof Source.Attr) {
            if (f.required()) {
                CodeBlock raw = CodeBlock.of("$T.INSTANCE.requireString($S, __raw_$L, __loc)",
                        CN_COERCIONS, f.name(), f.name());
                cb.addStatement("final $T __final_$L = $L", declared, f.name(),
                        coerceScalar(f, raw, CodeBlock.of("__loc"), converterRefs));
            } else {
                cb.addStatement("final $T __final_$L = (__raw_$L == null) ? null : $L",
                        declared, f.name(), f.name(),
                        coerceScalar(f, CodeBlock.of("__raw_$L", f.name()),
                                CodeBlock.of("__loc"), converterRefs));
            }
            return cb.build();
        }
        if (f.source() instanceof Source.Text) {
            cb.addStatement("final $T __final_$L = $L",
                    declared, f.name(),
                    coerceScalar(f, CodeBlock.of("__raw_$L", f.name()),
                            CodeBlock.of("__loc"), converterRefs));
            return cb.build();
        }
        // Source.Child or Source.PolyChild
        if (f.coerce() instanceof Coerce.Nested) {
            if (f.isList()) {
                cb.addStatement("final $T __final_$L = $T.unmodifiableList(__list_$L)",
                        declared, f.name(), CN_COLLECTIONS, f.name());
            } else if (f.required()) {
                cb.beginControlFlow("if (!__set_$L[0])", f.name())
                        .addStatement("throw new $T($S, __loc)", CN_MISSING_EX, f.name())
                        .endControlFlow();
                cb.addStatement("final $T __final_$L = __nested_$L[0]", declared, f.name(), f.name());
            } else {
                cb.addStatement("final $T __final_$L = __set_$L[0] ? __nested_$L[0] : null",
                        declared, f.name(), f.name(), f.name());
            }
            return cb.build();
        }
        // Scalar/temporal/decimal/custom child text.
        if (f.isList()) {
            TypeName elemBox = TypeRefs.toTypeName(f.elemType()).box();
            cb.addStatement("final $T<$T> __final_$L = new $T<>()", CN_LIST, elemBox, f.name(), CN_ARRAY_LIST);
            cb.beginControlFlow("for ($T __r : __list_$L)", ClassName.get(String.class), f.name());
            cb.addStatement("__final_$L.add($L)", f.name(),
                    coerceScalar(f, CodeBlock.of("__r"), CodeBlock.of("__loc"), converterRefs));
            cb.endControlFlow();
            return cb.build();
        }
        if (f.required()) {
            cb.beginControlFlow("if (!__set_$L[0])", f.name())
                    .addStatement("throw new $T($S, __loc)", CN_MISSING_EX, f.name())
                    .endControlFlow();
            cb.addStatement("final $T __final_$L = $L", declared, f.name(),
                    coerceScalar(f,
                            CodeBlock.of("__raw_$L[0]", f.name()),
                            CodeBlock.of("(__loc_$L[0] == null ? __loc : __loc_$L[0])", f.name(), f.name()),
                            converterRefs));
        } else {
            cb.addStatement("final $T __final_$L = (!__set_$L[0]) ? null : $L",
                    declared, f.name(), f.name(),
                    coerceScalar(f,
                            CodeBlock.of("__raw_$L[0]", f.name()),
                            CodeBlock.of("(__loc_$L[0] == null ? __loc : __loc_$L[0])", f.name(), f.name()),
                            converterRefs));
        }
        return cb.build();
    }

    private CodeBlock coerceScalar(FieldSpec f, CodeBlock raw, CodeBlock lc,
                                   Map<String, ConverterRef> converterRefs) {
        if (f.coerce() instanceof Coerce.AsString) return raw;
        if (f.coerce() instanceof Coerce.Custom c) {
            ConverterRef ref = converterRefs.get(c.converterFq());
            return CodeBlock.of("$L.convert($L, $L)", ref.varName, raw, lc);
        }
        if (f.coerce() instanceof Coerce.Scalar s) {
            return switch (s.kind()) {
                case INT -> CodeBlock.of("$T.INSTANCE.toInt($S, $L, $L)", CN_COERCIONS, f.name(), raw, lc);
                case LONG -> CodeBlock.of("$T.INSTANCE.toLong($S, $L, $L)", CN_COERCIONS, f.name(), raw, lc);
                case DOUBLE -> CodeBlock.of("$T.INSTANCE.toDouble($S, $L, $L)", CN_COERCIONS, f.name(), raw, lc);
                case BOOLEAN -> CodeBlock.of("$T.INSTANCE.toBoolean($S, $L, $L)", CN_COERCIONS, f.name(), raw, lc);
                default -> raw;
            };
        }
        if (f.coerce() instanceof Coerce.Temporal t) {
            return switch (t.kind()) {
                case LOCAL_DATE -> CodeBlock.of("$T.INSTANCE.toLocalDate($S, $L, $S, $L)",
                        CN_COERCIONS, f.name(), raw, t.pattern(), lc);
                case LOCAL_DATE_TIME -> CodeBlock.of("$T.INSTANCE.toLocalDateTime($S, $L, $S, $L)",
                        CN_COERCIONS, f.name(), raw, t.pattern(), lc);
                case INSTANT -> CodeBlock.of("$T.INSTANCE.toInstant($S, $L, $S, $L)",
                        CN_COERCIONS, f.name(), raw, t.pattern(), lc);
                default -> raw;
            };
        }
        if (f.coerce() instanceof Coerce.Decimal d) {
            return CodeBlock.of("$T.INSTANCE.toBigDecimal($S, $L, $S, $L)",
                    CN_COERCIONS, f.name(), raw, d.pattern(), lc);
        }
        return raw;
    }

    private CodeBlock nsLiteral(String ns) {
        if (ns == null) return CodeBlock.of("null");
        return CodeBlock.of("$S", ns);
    }

    private CodeBlock nsMatchExprVar(String ns, String var) {
        if (ns == null) return CodeBlock.of("($L == null || c.getIgnoreNamespace())", var);
        return CodeBlock.of("($S.equals($L) || c.getIgnoreNamespace())", ns, var);
    }

    /**
     * Emits {@code int[] __cnt_<slot> = new int[]{0};} declarations for the precomputed slots.
     */
    private void declareSlotsCode(CodeBlock.Builder cb, SlotTable slots) {
        for (var e : slots) {
            cb.addStatement("final int[] __cnt_$L = new int[]{0}", e.getValue());
        }
    }

    /**
     * Emits {@code if/else if} arms over a {@code groupChildrenByQKey} map, one per unique
     * base {@link QKey}, into an open chain. Caller closes the chain via
     * {@link CodeBlock.Builder#endControlFlow()} (or with a trailing
     * {@code nextControlFlow("else")} clause). Returns the updated {@code first} flag so callers
     * can chain additional sibling arms (map entries, polymorphic variants, etc.).
     */
    private boolean emitGroupedChildArms(CodeBlock.Builder cb,
                                         Map<QKey, List<Map.Entry<List<Predicate>, TrieNode>>> grouped,
                                         boolean first,
                                         SlotTable slots,
                                         NestedRegistry registry,
                                         Map<String, ConverterRef> converterRefs,
                                         String lnVar, String nsVar) {
        for (var entry : grouped.entrySet()) {
            QKey key = entry.getKey();
            String fmt = "$S.equals($L) && $L";
            if (first) {
                cb.beginControlFlow("if (" + fmt + ")", key.local(), lnVar, nsMatchExprVar(key.ns(), nsVar));
            } else {
                cb.nextControlFlow("else if (" + fmt + ")", key.local(), lnVar, nsMatchExprVar(key.ns(), nsVar));
            }
            first = false;
            emitPredicateBranches(cb, key, entry.getValue(), slots, registry, converterRefs);
        }
        return first;
    }

    /**
     * Two-pass dispatch when predicate variants overlap on the same element:
     * 1. attr-only reads run for EVERY matching predicate (childAttr is a pure lookup, no
     * element consumption). Without this, paths like
     * link[@type='epub']/@href
     * link[@type='epub'][@rel='acq']/@href
     * would race and only the first matching arm would fire.
     * 2. Body-consuming variants (text / nested / descend) dispatch first-match-wins —
     * a single element body can only be consumed once.
     */
    private void emitPredicateBranches(CodeBlock.Builder cb,
                                       QKey qkey,
                                       List<Map.Entry<List<Predicate>, TrieNode>> branches,
                                       SlotTable slots,
                                       NestedRegistry registry,
                                       Map<String, ConverterRef> converterRefs) {
        // Per-element pre-compute: increment any counters that key on this qname BEFORE the
        // two-pass dispatch. Each element produces exactly one increment per slot, regardless of
        // how many attr-only / body branches reference that slot.
        for (var slotEntry : slots) {
            PrefixKey key = slotEntry.getKey();
            if (!key.qkey().equals(qkey)) continue;
            String name = slotEntry.getValue();
            if (key.prefix().isEmpty()) {
                // No prefix guard — unconditionally increment.
                cb.addStatement("final int __pos_$L = ++__cnt_$L[0]", name, name);
            } else {
                Predicate folded = key.prefix().get(0);
                for (int i = 1; i < key.prefix().size(); i++) {
                    folded = new Predicate.And(folded, key.prefix().get(i));
                }
                CodeBlock preExpr = plainPredicateExpr(folded);
                cb.addStatement("final boolean __pre_$L = $L", name, preExpr);
                cb.addStatement("final int __pos_$L = __pre_$L ? ++__cnt_$L[0] : 0", name, name, name);
            }
        }

        if (branches.size() == 1 && branches.get(0).getKey().isEmpty()) {
            emitChildBody(cb, branches.get(0).getValue(), registry, converterRefs);
            return;
        }
        for (var entry : branches) {
            TrieNode child = entry.getValue();
            if (child.attrEntries().isEmpty()) continue;
            List<Predicate> brackets = entry.getKey();
            CodeBlock cond = predicateExpr(brackets, qkey, slots);
            cb.beginControlFlow("if ($L)", cond);
            emitAttrEntries(cb, child);
            cb.endControlFlow();
        }
        List<Map.Entry<List<Predicate>, TrieNode>> bodyBranches = new ArrayList<>();
        for (var entry : branches) {
            if (entry.getValue().hasBodyContent()) bodyBranches.add(entry);
        }
        if (bodyBranches.isEmpty()) {
            cb.addStatement(SKIP_CHILD);
            return;
        }
        boolean first = true;
        for (var entry : bodyBranches) {
            List<Predicate> brackets = entry.getKey();
            CodeBlock cond = predicateExpr(brackets, qkey, slots);
            if (first) cb.beginControlFlow("if ($L)", cond);
            else cb.nextControlFlow("else if ($L)", cond);
            first = false;
            emitChildBodyContent(cb, entry.getValue(), registry, converterRefs);
        }
        cb.nextControlFlow("else");
        cb.addStatement(SKIP_CHILD);
        cb.endControlFlow();
    }

    /**
     * Emit a boolean expression for {@code brackets} in the context of {@code qkey}, optionally
     * referencing counter slots from {@code slots}. When any bracket contains a positional
     * {@link Predicate.Index}, the corresponding {@code __pre_<slot>}/{@code __pos_<slot>}
     * references are emitted; everything before the first Index becomes part of the slot's
     * prefix expression and everything after is appended as plain expressions.
     */
    private CodeBlock predicateExpr(List<Predicate> brackets, QKey qkey, SlotTable slots) {
        if (brackets.isEmpty()) return CodeBlock.of("true");
        if (!PredicateAnalysis.bracketsHaveIndex(brackets)) {
            Predicate folded = brackets.get(0);
            for (int i = 1; i < brackets.size(); i++) folded = new Predicate.And(folded, brackets.get(i));
            return plainPredicateExpr(folded);
        }
        int firstIdxIndex = -1;
        for (int i = 0; i < brackets.size(); i++) {
            if (PredicateAnalysis.containsIndex(brackets.get(i))) {
                firstIdxIndex = i;
                break;
            }
        }
        if (firstIdxIndex < 0) {
            throw new IllegalStateException("predicateExpr called with no Index in brackets — bug in bracketsHaveIndex");
        }
        List<Predicate> prefix = brackets.subList(0, firstIdxIndex);
        Predicate firstIdxBracket = brackets.get(firstIdxIndex);
        List<Predicate> suffix = brackets.subList(firstIdxIndex + 1, brackets.size());
        int n = PredicateAnalysis.firstIndexValue(firstIdxBracket);
        PrefixKey slotKey = new PrefixKey(qkey, PredicateAnalysis.prefixOfFirstIndex(brackets));
        String slotName = slots.get(slotKey);
        List<CodeBlock> parts = new ArrayList<>();
        // When the prefix is empty there is no __pre_ variable — the counter is always incremented.
        if (!prefix.isEmpty()) parts.add(CodeBlock.of("__pre_$L", slotName));
        parts.add(CodeBlock.of("(__pos_$L == $L)", slotName, n));
        // If the first-index bracket also contains non-Index predicates (e.g. `[2 and @x='y']`),
        // emit those alongside the position check.
        Predicate residual = PredicateAnalysis.stripIndex(firstIdxBracket);
        if (residual != null) parts.add(plainPredicateExpr(residual));
        // Suffix: every bracket after the one that introduced the Index. These are evaluated as
        // ordinary attribute predicates against the current element — they refine the position
        // match but do not affect counter incrementing.
        for (Predicate s : suffix) parts.add(plainPredicateExpr(s));
        CodeBlock acc = parts.get(0);
        for (int i = 1; i < parts.size(); i++) acc = CodeBlock.of("($L && $L)", acc, parts.get(i));
        return acc;
    }

    /**
     * Emit a boolean expression for an Index-free predicate. Equivalent to the legacy
     * {@code predicateExpr} minus the Index arm; descending into And/Or recurses through this same
     * function. Callers must guarantee {@code p} contains no {@link Predicate.Index}.
     */
    private CodeBlock plainPredicateExpr(Predicate p) {
        if (p instanceof Predicate.AttrEq ae) {
            String ns = ae.getName().getNs();
            CodeBlock nsLit = ns == null ? CodeBlock.of("null") : CodeBlock.of("$S", ns);
            String local = ae.getName().getLocal();
            String value = ae.getValue();
            if (ae.getNegate()) {
                // Mirror PathMatcher: missing attr satisfies !=, present-and-different also satisfies.
                return CodeBlock.of("(c.childAttr($L, $S) == null || !$S.equals(c.childAttr($L, $S)))",
                        nsLit, local, value, nsLit, local);
            }
            return CodeBlock.of("($S.equals(c.childAttr($L, $S)))", value, nsLit, local);
        }
        if (p instanceof Predicate.And and) {
            return CodeBlock.of("($L && $L)", plainPredicateExpr(and.getL()), plainPredicateExpr(and.getR()));
        }
        if (p instanceof Predicate.Or or) {
            return CodeBlock.of("($L || $L)", plainPredicateExpr(or.getL()), plainPredicateExpr(or.getR()));
        }
        if (p instanceof Predicate.Index) {
            throw new IllegalStateException("plainPredicateExpr called on Index — counter logic should have stripped this");
        }
        throw new IllegalStateException("unknown predicate: " + p);
    }
}
