package xmlfluss.apt;

import com.palantir.javapoet.*;
import xmlfluss.path.Predicate;

import javax.annotation.processing.Generated;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

/**
 * Generates the Java source for a {@code ${ClassName}Parser}. Renders both the
 * top-level record and any nested records discovered by the {@link Classifier}.
 */
final class Emitter {

    private static final ClassName CN_INPUT_STREAM = ClassName.get(InputStream.class);
    private static final ClassName CN_STREAM = ClassName.get("java.util.stream", "Stream");
    private static final ClassName CN_STREAM_SUPPORT = ClassName.get("java.util.stream", "StreamSupport");
    private static final ClassName CN_SPLITERATOR = ClassName.get("java.util", "Spliterator");
    private static final ClassName CN_ABSTRACT_SPLITERATOR = ClassName.get("java.util.Spliterators", "AbstractSpliterator");
    private static final ClassName CN_CONSUMER = ClassName.get(Consumer.class);
    private static final ClassName CN_LIST = ClassName.get("java.util", "List");
    private static final ClassName CN_ARRAY_LIST = ClassName.get("java.util", "ArrayList");
    private static final ClassName CN_COLLECTIONS = ClassName.get("java.util", "Collections");
    private static final ClassName CN_MAP = ClassName.get("java.util", "Map");
    private static final ClassName CN_LINKED_HASH_MAP = ClassName.get("java.util", "LinkedHashMap");
    private static final ClassName CN_OBJECTS = ClassName.get("java.util", "Objects");

    private static final ClassName CN_CURSOR = ClassName.get("xmlfluss.runtime", "XmlReadCursor");
    private static final ClassName CN_PATHS = ClassName.get("xmlfluss.runtime", "Paths");
    private static final ClassName CN_COMPILED_PATH = ClassName.get("xmlfluss.path", "CompiledPath");
    private static final ClassName CN_LOCATION = ClassName.get("xmlfluss", "Location");
    private static final ClassName CN_MISSING_EX = ClassName.get("xmlfluss", "XmlParseException", "Missing");
    private static final ClassName CN_COERCIONS = ClassName.get("xmlfluss.runtime", "Coercions");
    private static final ClassName CN_ADAPTER = ClassName.get("xmlfluss.runtime", "JavaCursorAdapter");

    private final ProcessingEnvironment env;

    Emitter(ProcessingEnvironment env) {
        this.env = env;
    }

    void emit(Model.RecordSpec topLevel, Model.NestedRegistry registry) {
        ClassName recordType = ClassName.get(topLevel.element());
        String parserName = topLevel.simpleName() + "Parser";

        TypeSpec.Builder cls = TypeSpec.classBuilder(parserName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addAnnotation(AnnotationSpec.builder(Generated.class)
                        .addMember("value", "$S", "xml-fluss-apt")
                        .addMember("date", "$S", LocalDate.now().toString())
                        .build())
                .addJavadoc("Generated by xml-fluss-apt — do not edit\n");

        cls.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE)
                .build());

        cls.addField(buildNsField(topLevel.nsMap()));

        cls.addField(FieldSpec.builder(CN_COMPILED_PATH, "PATH", Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                .initializer("$T.INSTANCE.compile($S, NS)",
                        CN_PATHS, topLevel.recordPath())
                .build());

        Map<String, ConverterRef> converterRefs = collectConverters(topLevel, registry);
        for (ConverterRef ref : converterRefs.values()) {
            cls.addField(FieldSpec.builder(ref.cls, ref.varName,
                            Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                    .initializer("new $T()", ref.cls)
                    .build());
        }

        TypeName streamOfRecord = ParameterizedTypeName.get(CN_STREAM, recordType);

        cls.addMethod(MethodSpec.methodBuilder("parse")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addParameter(CN_INPUT_STREAM, "input")
                .returns(streamOfRecord)
                .addStatement("return parse(input, false)")
                .build());

        MethodSpec.Builder parse = MethodSpec.methodBuilder("parse")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addParameter(CN_INPUT_STREAM, "input")
                .addParameter(TypeName.BOOLEAN, "ignoreNamespace")
                .returns(streamOfRecord);
        emitParseBody(parse, recordType);
        cls.addMethod(parse.build());

        MethodSpec.Builder buildOne = MethodSpec.methodBuilder("__buildRecord")
                .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
                .addParameter(CN_CURSOR, "c")
                .returns(recordType);
        buildOne.addCode(buildInstanceBody(recordType, topLevel.fields(), registry,
                converterRefs, /*record=*/true));
        cls.addMethod(buildOne.build());

        for (var entry : registry.byFq.entrySet()) {
            String fq = entry.getKey();
            Model.RecordSpec spec = entry.getValue();
            String helper = registry.helperByFq.get(fq);
            ClassName nestedType = ClassName.get(spec.element());
            MethodSpec.Builder helperMethod = MethodSpec.methodBuilder(helper)
                    .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
                    .addParameter(CN_CURSOR, "c")
                    .returns(nestedType);
            helperMethod.addCode(buildInstanceBody(nestedType, spec.fields(), registry,
                    converterRefs, /*record=*/false));
            cls.addMethod(helperMethod.build());
        }

        JavaFile file = JavaFile.builder(topLevel.packageName(), cls.build())
                .skipJavaLangImports(true)
                .build();
        try {
            file.writeTo(env.getFiler());
        } catch (IOException ioe) {
            env.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "xml-fluss-apt: failed to write " + parserName + ": " + ioe.getMessage(),
                    topLevel.element());
        }
    }

    private FieldSpec buildNsField(Map<String, String> nsMap) {
        TypeName mapType = ParameterizedTypeName.get(CN_MAP,
                ClassName.get("java.lang", "String"),
                ClassName.get("java.lang", "String"));
        FieldSpec.Builder b = FieldSpec.builder(mapType, "NS",
                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL);
        if (nsMap.isEmpty()) {
            b.initializer("$T.<$T,$T>emptyMap()", CN_COLLECTIONS,
                    ClassName.get(String.class), ClassName.get(String.class));
        } else if (nsMap.size() <= 10) {
            CodeBlock.Builder cb = CodeBlock.builder().add("$T.of(", CN_MAP);
            boolean first = true;
            for (var e : nsMap.entrySet()) {
                if (!first) cb.add(", ");
                first = false;
                cb.add("$S, $S", e.getKey(), e.getValue());
            }
            cb.add(")");
            b.initializer(cb.build());
        } else {
            CodeBlock.Builder cb = CodeBlock.builder()
                    .add("new $T<$T,$T>() {{", CN_LINKED_HASH_MAP,
                            ClassName.get(String.class), ClassName.get(String.class));
            for (var e : nsMap.entrySet()) {
                cb.add("\nput($S, $S);", e.getKey(), e.getValue());
            }
            cb.add("\n}}");
            b.initializer(cb.build());
        }
        return b.build();
    }

    private record ConverterRef(ClassName cls, String varName) {}

    private Map<String, ConverterRef> collectConverters(Model.RecordSpec topLevel,
                                                        Model.NestedRegistry registry) {
        Map<String, ConverterRef> out = new LinkedHashMap<>();
        for (Model.FieldSpec f : topLevel.fields()) registerConverter(out, f);
        for (Model.RecordSpec n : registry.byFq.values()) {
            for (Model.FieldSpec f : n.fields()) registerConverter(out, f);
        }
        return out;
    }

    private void registerConverter(Map<String, ConverterRef> sink, Model.FieldSpec f) {
        if (f.coerce() instanceof Model.Coerce.Custom c) {
            if (!sink.containsKey(c.converterFq())) {
                String varName = "__conv_" + sink.size();
                sink.put(c.converterFq(), new ConverterRef(c.converterClass(), varName));
            }
        }
        if (f.mapKeyField() != null) registerConverter(sink, f.mapKeyField());
        if (f.mapValueField() != null) registerConverter(sink, f.mapValueField());
    }

    private void emitParseBody(MethodSpec.Builder b, ClassName recordType) {
        TypeName spliteratorOfRec = ParameterizedTypeName.get(CN_SPLITERATOR, recordType);
        TypeName abstractSplOfRec = ParameterizedTypeName.get(CN_ABSTRACT_SPLITERATOR, recordType);
        TypeName streamOfRec = ParameterizedTypeName.get(CN_STREAM, recordType);
        TypeName consumerSuperRec = ParameterizedTypeName.get(CN_CONSUMER,
                WildcardTypeName.supertypeOf(recordType));

        TypeSpec spliteratorImpl = TypeSpec.anonymousClassBuilder(
                        "$T.MAX_VALUE, $T.ORDERED | $T.NONNULL",
                        ClassName.get("java.lang", "Long"), CN_SPLITERATOR, CN_SPLITERATOR)
                .superclass(abstractSplOfRec)
                .addMethod(MethodSpec.methodBuilder("tryAdvance")
                        .addAnnotation(Override.class)
                        .addModifiers(Modifier.PUBLIC)
                        .returns(TypeName.BOOLEAN)
                        .addParameter(ParameterSpec.builder(consumerSuperRec, "action").build())
                        .addStatement("if (!cursor.findNextRecord()) return false")
                        .addStatement("action.accept(__buildRecord(cursor))")
                        .addStatement("return true")
                        .build())
                .build();

        b.addStatement("final $T cursor = new $T(input, PATH, ignoreNamespace)", CN_CURSOR, CN_CURSOR);
        b.beginControlFlow("try");
        b.addStatement("$T splr = $L", spliteratorOfRec, spliteratorImpl);
        b.addStatement("$T stream = $T.stream(splr, false)", streamOfRec, CN_STREAM_SUPPORT);
        b.addStatement("return stream.onClose(cursor::close)");
        b.endControlFlow();
        b.beginControlFlow("catch ($T t)", ClassName.get("java.lang", "Throwable"));
        b.beginControlFlow("try");
        b.addStatement("cursor.close()");
        b.endControlFlow();
        b.beginControlFlow("catch ($T ignored)", ClassName.get("java.lang", "Throwable"));
        b.endControlFlow();
        b.addStatement("throw t");
        b.endControlFlow();
    }

    private CodeBlock buildInstanceBody(ClassName type,
                                        List<Model.FieldSpec> fields,
                                        Model.NestedRegistry registry,
                                        Map<String, ConverterRef> converterRefs,
                                        boolean record) {
        String attrFn = record ? "recordAttr" : "childAttr";
        String forEachFn = record ? "forEachRecordChild" : "forEachSubrecordChild";
        String textFn = record ? "recordText" : "subrecordText";
        String locFn = record ? "recordLocation" : "childLocation";

        CodeBlock.Builder cb = CodeBlock.builder();
        cb.addStatement("final $T __loc = c.$L()", CN_LOCATION, locFn);

        // Read attributes immediately.
        for (Model.FieldSpec f : fields) {
            if (!(f.source() instanceof Model.Source.Attr a)) continue;
            cb.addStatement("final $T __raw_$L = c.$L($L, $S)",
                    ClassName.get(String.class), f.name(), attrFn, nsLiteral(a.ns()), a.name());
        }

        Model.FieldSpec textField = null;
        boolean hasChildOrText = false;
        for (Model.FieldSpec f : fields) {
            if (f.source() instanceof Model.Source.Text) {
                textField = f;
                hasChildOrText = true;
                continue;
            }
            if (f.source() instanceof Model.Source.Child
                    || f.source() instanceof Model.Source.PolyChild) {
                hasChildOrText = true;
                emitFieldStateInit(cb, f);
            } else if (f.source() instanceof Model.Source.MapEntry) {
                hasChildOrText = true;
                emitMapStateInit(cb, f);
            }
        }

        if (hasChildOrText) {
            // Build trie of direct children (non-descendant @XmlChild fields).
            TrieNode root = new TrieNode();
            List<Model.FieldSpec> descendantFields = new ArrayList<>();
            List<Model.FieldSpec> mapFields = new ArrayList<>();
            List<Model.FieldSpec> polyFields = new ArrayList<>();
            for (Model.FieldSpec f : fields) {
                if (f.source() instanceof Model.Source.Child sc) {
                    if (sc.descendant()) descendantFields.add(f);
                    else insertIntoTrie(root, sc.segments(), f);
                } else if (f.source() instanceof Model.Source.MapEntry) {
                    mapFields.add(f);
                } else if (f.source() instanceof Model.Source.PolyChild) {
                    polyFields.add(f);
                }
            }

            // Counter slots must be declared OUTSIDE the per-sibling lambda so that ++__cnt[0]
            // accumulates across siblings rather than resetting per iteration.
            Map<PrefixKey, String> slots = declareCounterSlots(cb, groupChildrenByQKey(root));
            cb.add("$T.$L(c, (ln, ns) -> {\n", CN_ADAPTER, forEachFn).indent();
            emitTopLevelChildSwitch(cb, root, slots, descendantFields, mapFields, polyFields, registry, converterRefs, "ln", "ns");
            cb.unindent().add("});\n");

            if (textField != null) {
                boolean preserve = ((Model.Source.Text) textField.source()).preserveWhitespace();
                cb.addStatement("final $T __raw_$L = c.$L($L)",
                        ClassName.get(String.class), textField.name(), textFn, preserve);
            }
        }

        // Coerce per field, build constructor args.
        List<String> ctorArgs = new ArrayList<>();
        for (Model.FieldSpec f : fields) {
            ctorArgs.add("__final_" + f.name());
            cb.add(coerceField(f, converterRefs));
        }

        StringBuilder args = new StringBuilder();
        for (int i = 0; i < ctorArgs.size(); i++) {
            if (i > 0) args.append(", ");
            args.append(ctorArgs.get(i));
        }
        cb.addStatement("return new $T($L)", type, args.toString());
        return cb.build();
    }

    /** Emit per-field state holders. */
    private void emitFieldStateInit(CodeBlock.Builder cb, Model.FieldSpec f) {
        if (f.source() instanceof Model.Source.Text) return;
        if (f.coerce() instanceof Model.Coerce.Nested) {
            if (f.isList()) {
                cb.addStatement("final $T<$T> __list_$L = new $T<>()",
                        CN_LIST, f.elemTypeName().box(), f.name(), CN_ARRAY_LIST);
            } else {
                cb.addStatement("final $T[] __nested_$L = new $T[1]",
                        f.elemTypeName().box(), f.name(), f.elemTypeName().box());
                cb.addStatement("final boolean[] __set_$L = new boolean[1]", f.name());
            }
        } else if (f.isList()) {
            cb.addStatement("final $T<$T> __list_$L = new $T<>()",
                    CN_LIST, ClassName.get(String.class), f.name(), CN_ARRAY_LIST);
        } else {
            cb.addStatement("final $T[] __raw_$L = new $T[1]",
                    ClassName.get(String.class), f.name(), ClassName.get(String.class));
            cb.addStatement("final $T[] __loc_$L = new $T[1]", CN_LOCATION, f.name(), CN_LOCATION);
            cb.addStatement("final boolean[] __set_$L = new boolean[1]", f.name());
        }
    }

    private void emitMapStateInit(CodeBlock.Builder cb, Model.FieldSpec f) {
        Model.FieldSpec keyF = f.mapKeyField();
        Model.FieldSpec valF = f.mapValueField();
        TypeName keyT = keyF.fieldType().box();
        TypeName valStored = valF.isList()
                ? ParameterizedTypeName.get(CN_LIST, valF.elemTypeName().box())
                : valF.fieldType().box();
        TypeName mapT = ParameterizedTypeName.get(CN_LINKED_HASH_MAP, keyT, valStored);
        cb.addStatement("final $T __map_$L = new $T<>()", mapT, f.name(), CN_LINKED_HASH_MAP);
        if (!f.required()) {
            cb.addStatement("final boolean[] __set_$L = new boolean[1]", f.name());
        }
    }

    /** Top-level child dispatch switch shared between record and nested helpers. */
    private void emitTopLevelChildSwitch(CodeBlock.Builder cb, TrieNode directRoot,
                                         Map<PrefixKey, String> slots,
                                         List<Model.FieldSpec> descendantFields,
                                         List<Model.FieldSpec> mapFields,
                                         List<Model.FieldSpec> polyFields,
                                         Model.NestedRegistry registry,
                                         Map<String, ConverterRef> converterRefs,
                                         String lnVar, String nsVar) {
        if (directRoot.children.isEmpty() && descendantFields.isEmpty()
                && mapFields.isEmpty() && polyFields.isEmpty()) {
            cb.addStatement("c.skipChild()");
            return;
        }
        // Group descendant fields by head qname (brackets kept alongside).
        Map<Model.QKey, List<Map.Entry<List<Predicate>, Model.FieldSpec>>> byHead = new LinkedHashMap<>();
        for (Model.FieldSpec f : descendantFields) {
            Model.PathSeg.Element head = (Model.PathSeg.Element) ((Model.Source.Child) f.source()).segments().get(0);
            byHead.computeIfAbsent(new Model.QKey(head.ns(), head.name()), k -> new ArrayList<>())
                    .add(new java.util.AbstractMap.SimpleEntry<>(head.brackets(), f));
        }

        boolean first = true;
        // Direct children, grouped by base QKey (predicate variants dispatched inside).
        var groupedDirect = groupChildrenByQKey(directRoot);
        for (var entry : groupedDirect.entrySet()) {
            Model.QKey key = entry.getKey();
            String prefix = first ? "if " : "else if ";
            first = false;
            cb.add("$L($S.equals($L) && $L) {\n", prefix, key.local(), lnVar, nsMatchExprVar(key.ns(), nsVar)).indent();
            emitPredicateBranches(cb, key, entry.getValue(), slots, registry, converterRefs);
            cb.unindent().add("}\n");
        }
        // Map entry arms.
        for (Model.FieldSpec mf : mapFields) {
            Model.Source.MapEntry me = (Model.Source.MapEntry) mf.source();
            String prefix = first ? "if " : "else if ";
            first = false;
            cb.add("$L($S.equals($L) && $L) {\n", prefix, me.entryLocal(), lnVar, nsMatchExprVar(me.entryNs(), nsVar)).indent();
            emitMapEntryCase(cb, mf, registry, converterRefs);
            cb.unindent().add("}\n");
        }
        // Polymorphic arms.
        for (Model.FieldSpec pf : polyFields) {
            Model.PolyDispatch d = ((Model.Source.PolyChild) pf.source()).dispatch();
            if (d instanceof Model.PolyDispatch.Tag tag) {
                for (Model.TagVariant v : tag.variants()) {
                    String prefix = first ? "if " : "else if ";
                    first = false;
                    cb.add("$L($S.equals($L) && $L) {\n", prefix, v.local(), lnVar, nsMatchExprVar(v.ns(), nsVar)).indent();
                    emitPolyAssign(cb, pf, v.subtypeFq(), registry);
                    cb.unindent().add("}\n");
                }
            } else if (d instanceof Model.PolyDispatch.Attr ad) {
                String prefix = first ? "if " : "else if ";
                first = false;
                cb.add("$L($S.equals($L) && $L) {\n", prefix, ad.wrapLocal(), lnVar, nsMatchExprVar(ad.wrapNs(), nsVar)).indent();
                emitPolyAttrSwitch(cb, pf, ad, registry);
                cb.unindent().add("}\n");
            }
        }
        // Descendant heads as direct matches.
        for (var entry : byHead.entrySet()) {
            Model.QKey head = entry.getKey();
            String prefix = first ? "if " : "else if ";
            first = false;
            cb.add("$L($S.equals($L) && $L) {\n", prefix, head.local(), lnVar, nsMatchExprVar(head.ns(), nsVar)).indent();
            emitDescendantArm(cb, head, entry.getValue(), registry, converterRefs, /*terminating=*/false);
            cb.unindent().add("}\n");
        }
        // Else: descendant scan or skipChild.
        if (byHead.isEmpty()) {
            if (first) {
                cb.addStatement("c.skipChild()");
            } else {
                cb.add("else {\n").indent();
                cb.addStatement("c.skipChild()");
                cb.unindent().add("}\n");
            }
        } else {
            cb.add("else {\n").indent();
            cb.add("$T.forEachDescendantInChild(c, (dln, dns) -> {\n", CN_ADAPTER).indent();
            boolean dfirst = true;
            for (var entry : byHead.entrySet()) {
                Model.QKey head = entry.getKey();
                String prefix = dfirst ? "if " : "else if ";
                dfirst = false;
                cb.add("$L($S.equals(dln) && $L) {\n", prefix, head.local(),
                        nsMatchExprVar(head.ns(), "dns")).indent();
                emitDescendantArm(cb, head, entry.getValue(), registry, converterRefs, /*terminating=*/true);
                cb.unindent().add("}\n");
            }
            cb.add("return false;\n");
            cb.unindent().add("});\n");
            cb.unindent().add("}\n");
        }
    }

    /** One arm of the descendant dispatch — head matched, walk tail or read leaf. */
    private void emitDescendantArm(CodeBlock.Builder cb,
                                   Model.QKey head,
                                   List<Map.Entry<List<Predicate>, Model.FieldSpec>> branches,
                                   Model.NestedRegistry registry,
                                   Map<String, ConverterRef> converterRefs,
                                   boolean terminating) {
        // The descendant-axis head segment cannot carry a positional predicate (rejected by
        // validateChildPredicate), so brackets here are guaranteed Index-free. We can still have
        // attribute-equality predicates that select among descendant heads.
        List<Model.FieldSpec> unguarded = new ArrayList<>();
        List<Map.Entry<List<Predicate>, Model.FieldSpec>> guarded = new ArrayList<>();
        for (var entry : branches) {
            if (entry.getKey().isEmpty()) unguarded.add(entry.getValue());
            else guarded.add(entry);
        }
        if (guarded.isEmpty()) {
            emitDescendantArmBody(cb, unguarded, registry, converterRefs);
            if (terminating) cb.add("return true;\n");
            return;
        }
        boolean first = true;
        for (var entry : guarded) {
            String prefix = first ? "if " : "else if ";
            first = false;
            CodeBlock cond = predicateExpr(entry.getKey(), head, java.util.Map.of());
            cb.add("$L($L) {\n", prefix, cond).indent();
            emitDescendantArmBody(cb, List.of(entry.getValue()), registry, converterRefs);
            if (terminating) cb.add("return true;\n");
            cb.unindent().add("}\n");
        }
        if (!unguarded.isEmpty()) {
            cb.add("else {\n").indent();
            emitDescendantArmBody(cb, unguarded, registry, converterRefs);
            if (terminating) cb.add("return true;\n");
            cb.unindent().add("}\n");
        } else if (terminating) {
            // No matching predicate variant: fall through, do not consume.
        }
    }

    private void emitDescendantArmBody(CodeBlock.Builder cb,
                                       List<Model.FieldSpec> headFields, Model.NestedRegistry registry,
                                       Map<String, ConverterRef> converterRefs) {
        boolean anyEmpty = headFields.stream()
                .anyMatch(f -> ((Model.Source.Child) f.source()).segments().size() == 1);
        boolean anyNonEmpty = headFields.stream()
                .anyMatch(f -> ((Model.Source.Child) f.source()).segments().size() > 1);
        if (anyEmpty && anyNonEmpty) {
            cb.add("// invalid mix — caught at validateChildPaths\n");
        }
        if (anyEmpty) {
            // Single field consuming the head element directly.
            Model.FieldSpec leaf = headFields.get(0);
            emitLeafReadInline(cb, leaf, registry);
        } else {
            // Tail trie: walk children.
            TrieNode tailTrie = new TrieNode();
            for (Model.FieldSpec f : headFields) {
                List<Model.PathSeg> segs = ((Model.Source.Child) f.source()).segments();
                insertIntoTrie(tailTrie, segs.subList(1, segs.size()), f);
            }
            emitChildBody(cb, tailTrie, registry, converterRefs);
        }
    }

    /** Read a single leaf (head=field) inline at descendant matching site. */
    private void emitLeafReadInline(CodeBlock.Builder cb, Model.FieldSpec f,
                                    Model.NestedRegistry registry) {
        if (f.coerce() instanceof Model.Coerce.Nested n) {
            String helper = registry.helperByFq.get(n.typeFq());
            if (f.isList()) {
                cb.addStatement("__list_$L.add($L(c))", f.name(), helper);
            } else {
                cb.addStatement("__nested_$L[0] = $L(c)", f.name(), helper);
                cb.addStatement("__set_$L[0] = true", f.name());
            }
        } else {
            if (f.isList()) {
                cb.addStatement("__list_$L.add(c.childText(false))", f.name());
            } else {
                cb.addStatement("__loc_$L[0] = c.childLocation()", f.name());
                cb.addStatement("__raw_$L[0] = c.childText(false)", f.name());
                cb.addStatement("__set_$L[0] = true", f.name());
            }
        }
    }

    /** Walk a trie at a non-root node — at the cursor's current child element. */
    private void emitChildBody(CodeBlock.Builder cb, TrieNode node,
                               Model.NestedRegistry registry,
                               Map<String, ConverterRef> converterRefs) {
        emitAttrEntries(cb, node);
        emitChildBodyContent(cb, node, registry, converterRefs);
    }

    /** Pure attr reads — safe to run multiple times for overlapping predicate variants. */
    private void emitAttrEntries(CodeBlock.Builder cb, TrieNode node) {
        for (var ae : node.attrEntries) {
            Model.FieldSpec f = ae.field();
            cb.beginControlFlow("");
            cb.addStatement("$T __a = c.childAttr($L, $S)",
                    ClassName.get(String.class), nsLiteral(ae.ns()), ae.name());
            cb.beginControlFlow("if (__a != null)");
            if (f.isList()) {
                cb.addStatement("__list_$L.add(__a)", f.name());
            } else {
                cb.addStatement("__raw_$L[0] = __a", f.name());
                cb.addStatement("__loc_$L[0] = c.childLocation()", f.name());
                cb.addStatement("__set_$L[0] = true", f.name());
            }
            cb.endControlFlow();
            cb.endControlFlow();
        }
    }

    /** Per-emitter counter for nested lambda variable names — Java forbids shadowing. */
    private int lambdaDepth = 0;

    /** Body-consuming dispatch — text / nested / descend. Caller decides whether to gate it. */
    @SuppressWarnings("StatementWithEmptyBody")
    private void emitChildBodyContent(CodeBlock.Builder cb, TrieNode node,
                                      Model.NestedRegistry registry,
                                      Map<String, ConverterRef> converterRefs) {
        boolean hasText = !node.textEntries.isEmpty();
        boolean hasNested = !node.nestedEntries.isEmpty();
        boolean hasDescend = !node.children.isEmpty();
        if (hasNested) {
            for (Model.FieldSpec f : node.nestedEntries) {
                String helper = registry.helperByFq.get(((Model.Coerce.Nested) f.coerce()).typeFq());
                if (f.isList()) {
                    cb.addStatement("__list_$L.add($L(c))", f.name(), helper);
                } else {
                    cb.addStatement("__nested_$L[0] = $L(c)", f.name(), helper);
                    cb.addStatement("__set_$L[0] = true", f.name());
                }
            }
        } else if (hasText) {
            cb.addStatement("$T __t_loc = c.childLocation()", CN_LOCATION);
            cb.addStatement("$T __t = c.childText(false)", ClassName.get(String.class));
            for (Model.FieldSpec f : node.textEntries) {
                if (f.isList()) {
                    cb.addStatement("__list_$L.add(__t)", f.name());
                } else {
                    cb.addStatement("__raw_$L[0] = __t", f.name());
                    cb.addStatement("__loc_$L[0] = __t_loc", f.name());
                    cb.addStatement("__set_$L[0] = true", f.name());
                }
            }
        } else if (hasDescend) {
            // Lambda var names suffixed by depth — Java forbids shadowing nested lambda
            // params, so each `forEachChild` callback needs unique cln/cns identifiers.
            int depth = ++lambdaDepth;
            String lnVar = depth == 1 ? "cln" : "cln" + depth;
            String nsVar = depth == 1 ? "cns" : "cns" + depth;
            // Counter slots for direct edges under `node` must outlive the per-sibling lambda
            // — declare them here, BEFORE entering forEachChild, so increments accumulate
            // across siblings of the same parent.
            Map<PrefixKey, String> slots = declareCounterSlots(cb, groupChildrenByQKey(node));
            cb.add("$T.forEachChild(c, ($L, $L) -> {\n", CN_ADAPTER, lnVar, nsVar).indent();
            emitChildrenSwitch(cb, node, slots, registry, converterRefs, lnVar, nsVar);
            cb.unindent().add("});\n");
            lambdaDepth--;
        } else {
            // node has only attrs, no element drains needed; cursor already positioned at the element.
            // Element body untouched: forEach* call site will skip leftovers.
        }
    }

    private void emitChildrenSwitch(CodeBlock.Builder cb, TrieNode node,
                                    Map<PrefixKey, String> slots,
                                    Model.NestedRegistry registry,
                                    Map<String, ConverterRef> converterRefs,
                                    String lnVar, String nsVar) {
        if (node.children.isEmpty()) {
            cb.addStatement("c.skipChild()");
            return;
        }
        var grouped = groupChildrenByQKey(node);
        boolean first = true;
        for (var entry : grouped.entrySet()) {
            Model.QKey k = entry.getKey();
            String prefix = first ? "if " : "else if ";
            first = false;
            cb.add("$L($S.equals($L) && $L) {\n", prefix, k.local(), lnVar, nsMatchExprVar(k.ns(), nsVar)).indent();
            emitPredicateBranches(cb, k, entry.getValue(), slots, registry, converterRefs);
            cb.unindent().add("}\n");
        }
        cb.add("else {\n").indent();
        cb.addStatement("c.skipChild()");
        cb.unindent().add("}\n");
    }

    private void emitPolyAssign(CodeBlock.Builder cb, Model.FieldSpec f, String subtypeFq,
                                Model.NestedRegistry registry) {
        String helper = registry.helperByFq.get(subtypeFq);
        if (f.isList()) {
            cb.addStatement("__list_$L.add($L(c))", f.name(), helper);
        } else {
            cb.addStatement("__nested_$L[0] = $L(c)", f.name(), helper);
            cb.addStatement("__set_$L[0] = true", f.name());
        }
    }

    private void emitPolyAttrSwitch(CodeBlock.Builder cb, Model.FieldSpec f,
                                    Model.PolyDispatch.Attr d, Model.NestedRegistry registry) {
        cb.addStatement("$T __disc_$L = c.childAttr($L, $S)",
                ClassName.get(String.class), f.name(), nsLiteral(d.attrNs()), d.attrLocal());
        boolean first = true;
        for (Model.AttrVariant v : d.variants()) {
            String prefix = first ? "if " : "else if ";
            first = false;
            cb.add("$L($T.equals(__disc_$L, $S)) {\n", prefix, CN_OBJECTS, f.name(), v.value()).indent();
            emitPolyAssign(cb, f, v.subtypeFq(), registry);
            cb.unindent().add("}\n");
        }
        cb.add("else {\n").indent();
        cb.addStatement("c.skipChild()");
        cb.unindent().add("}\n");
    }

    /** Build map entry: read key + value via synthetic specs, then store in __map_X. */
    private void emitMapEntryCase(CodeBlock.Builder cb, Model.FieldSpec f,
                                  Model.NestedRegistry registry,
                                  Map<String, ConverterRef> converterRefs) {
        Model.FieldSpec keyF = f.mapKeyField();
        Model.FieldSpec valF = f.mapValueField();
        for (Model.FieldSpec sf : List.of(keyF, valF)) {
            if (sf.source() instanceof Model.Source.Attr a) {
                if (sf.isList()) {
                    cb.addStatement("final $T<$T> __list_$L = new $T<>()",
                            CN_LIST, ClassName.get(String.class), sf.name(), CN_ARRAY_LIST);
                    cb.beginControlFlow("");
                    cb.addStatement("$T __a = c.childAttr($L, $S)",
                            ClassName.get(String.class), nsLiteral(a.ns()), a.name());
                    cb.beginControlFlow("if (__a != null)");
                    cb.addStatement("__list_$L.add(__a)", sf.name());
                    cb.endControlFlow();
                    cb.endControlFlow();
                } else {
                    cb.addStatement("final $T __raw_$L = c.childAttr($L, $S)",
                            ClassName.get(String.class), sf.name(), nsLiteral(a.ns()), a.name());
                }
            } else {
                emitFieldStateInit(cb, sf);
            }
        }
        // Build trie of synthetic child fields (direct + descendant).
        TrieNode root = new TrieNode();
        List<Model.FieldSpec> descend = new ArrayList<>();
        for (Model.FieldSpec sf : List.of(keyF, valF)) {
            if (sf.source() instanceof Model.Source.Child sc) {
                if (sc.descendant()) descend.add(sf);
                else insertIntoTrie(root, sc.segments(), sf);
            }
        }
        if (!root.children.isEmpty() || !descend.isEmpty()) {
            Map<PrefixKey, String> mapSlots = declareCounterSlots(cb, groupChildrenByQKey(root));
            cb.add("$T.forEachSubrecordChild(c, (mln, mns) -> {\n", CN_ADAPTER).indent();
            emitTopLevelChildSwitch(cb, root, mapSlots, descend, List.of(), List.of(), registry, converterRefs, "mln", "mns");
            cb.unindent().add("});\n");
        }
        // Coerce key + value, store.
        cb.add(coerceField(keyF, converterRefs));
        cb.add(coerceField(valF, converterRefs));
        if (valF.isList()) {
            cb.addStatement("__map_$L.computeIfAbsent(__final_$L, __k -> new $T<>()).addAll(__final_$L)",
                    f.name(), keyF.name(), CN_ARRAY_LIST, valF.name());
        } else {
            cb.addStatement("__map_$L.put(__final_$L, __final_$L)", f.name(), keyF.name(), valF.name());
        }
        if (!f.required()) {
            cb.addStatement("__set_$L[0] = true", f.name());
        }
    }

    /** Emits {@code final T __final_name = ...;} for one field. */
    private CodeBlock coerceField(Model.FieldSpec f,
                                  Map<String, ConverterRef> converterRefs) {
        CodeBlock.Builder cb = CodeBlock.builder();
        TypeName declared = f.fieldType();

        if (f.coerce() instanceof Model.Coerce.MapAggregate) {
            if (f.required()) {
                cb.addStatement("final $T __final_$L = $T.unmodifiableMap(__map_$L)",
                        declared, f.name(), CN_COLLECTIONS, f.name());
            } else {
                cb.addStatement("final $T __final_$L = (!__set_$L[0]) ? null : $T.unmodifiableMap(__map_$L)",
                        declared, f.name(), f.name(), CN_COLLECTIONS, f.name());
            }
            return cb.build();
        }

        if (f.source() instanceof Model.Source.Attr) {
            if (f.required()) {
                CodeBlock raw = CodeBlock.of("$T.INSTANCE.requireString($S, __raw_$L, __loc)",
                        CN_COERCIONS, f.name(), f.name());
                cb.addStatement("final $T __final_$L = $L", declared, f.name(),
                        coerceScalar(f, raw, CodeBlock.of("__loc"), converterRefs));
            } else {
                cb.addStatement("final $T __final_$L = (__raw_$L == null) ? null : $L",
                        declared, f.name(), f.name(),
                        coerceScalar(f, CodeBlock.of("__raw_$L", f.name()),
                                CodeBlock.of("__loc"), converterRefs));
            }
            return cb.build();
        }
        if (f.source() instanceof Model.Source.Text) {
            cb.addStatement("final $T __final_$L = $L",
                    declared, f.name(),
                    coerceScalar(f, CodeBlock.of("__raw_$L", f.name()),
                            CodeBlock.of("__loc"), converterRefs));
            return cb.build();
        }
        // Source.Child or Source.PolyChild
        if (f.coerce() instanceof Model.Coerce.Nested) {
            if (f.isList()) {
                cb.addStatement("final $T __final_$L = $T.unmodifiableList(__list_$L)",
                        declared, f.name(), CN_COLLECTIONS, f.name());
            } else if (f.required()) {
                cb.beginControlFlow("if (!__set_$L[0])", f.name())
                        .addStatement("throw new $T($S, __loc)", CN_MISSING_EX, f.name())
                        .endControlFlow();
                cb.addStatement("final $T __final_$L = __nested_$L[0]", declared, f.name(), f.name());
            } else {
                cb.addStatement("final $T __final_$L = __set_$L[0] ? __nested_$L[0] : null",
                        declared, f.name(), f.name(), f.name());
            }
            return cb.build();
        }
        // Scalar/temporal/decimal/custom child text.
        if (f.isList()) {
            cb.addStatement("final $T<$T> __final_$L = new $T<>()", CN_LIST, f.elemTypeName().box(), f.name(), CN_ARRAY_LIST);
            cb.beginControlFlow("for ($T __r : __list_$L)", ClassName.get(String.class), f.name());
            cb.addStatement("__final_$L.add($L)", f.name(),
                    coerceScalar(f, CodeBlock.of("__r"), CodeBlock.of("__loc"), converterRefs));
            cb.endControlFlow();
            return cb.build();
        }
        if (f.required()) {
            cb.beginControlFlow("if (!__set_$L[0])", f.name())
                    .addStatement("throw new $T($S, __loc)", CN_MISSING_EX, f.name())
                    .endControlFlow();
            cb.addStatement("final $T __final_$L = $L", declared, f.name(),
                    coerceScalar(f,
                            CodeBlock.of("__raw_$L[0]", f.name()),
                            CodeBlock.of("(__loc_$L[0] == null ? __loc : __loc_$L[0])", f.name(), f.name()),
                            converterRefs));
        } else {
            cb.addStatement("final $T __final_$L = (!__set_$L[0]) ? null : $L",
                    declared, f.name(), f.name(),
                    coerceScalar(f,
                            CodeBlock.of("__raw_$L[0]", f.name()),
                            CodeBlock.of("(__loc_$L[0] == null ? __loc : __loc_$L[0])", f.name(), f.name()),
                            converterRefs));
        }
        return cb.build();
    }

    private CodeBlock coerceScalar(Model.FieldSpec f, CodeBlock raw, CodeBlock lc,
                                   Map<String, ConverterRef> converterRefs) {
        if (f.coerce() instanceof Model.Coerce.AsString) return raw;
        if (f.coerce() instanceof Model.Coerce.Custom c) {
            ConverterRef ref = converterRefs.get(c.converterFq());
            return CodeBlock.of("$L.convert($L, $L)", ref.varName, raw, lc);
        }
        if (f.coerce() instanceof Model.Coerce.Scalar s) {
            return switch (s.kind()) {
                case INT -> CodeBlock.of("$T.INSTANCE.toInt($S, $L, $L)", CN_COERCIONS, f.name(), raw, lc);
                case LONG -> CodeBlock.of("$T.INSTANCE.toLong($S, $L, $L)", CN_COERCIONS, f.name(), raw, lc);
                case DOUBLE -> CodeBlock.of("$T.INSTANCE.toDouble($S, $L, $L)", CN_COERCIONS, f.name(), raw, lc);
                case BOOLEAN -> CodeBlock.of("$T.INSTANCE.toBoolean($S, $L, $L)", CN_COERCIONS, f.name(), raw, lc);
                default -> raw;
            };
        }
        if (f.coerce() instanceof Model.Coerce.Temporal t) {
            return switch (t.kind()) {
                case LOCAL_DATE -> CodeBlock.of("$T.INSTANCE.toLocalDate($S, $L, $S, $L)",
                        CN_COERCIONS, f.name(), raw, t.pattern(), lc);
                case LOCAL_DATE_TIME -> CodeBlock.of("$T.INSTANCE.toLocalDateTime($S, $L, $S, $L)",
                        CN_COERCIONS, f.name(), raw, t.pattern(), lc);
                case INSTANT -> CodeBlock.of("$T.INSTANCE.toInstant($S, $L, $S, $L)",
                        CN_COERCIONS, f.name(), raw, t.pattern(), lc);
                default -> raw;
            };
        }
        if (f.coerce() instanceof Model.Coerce.Decimal d) {
            return CodeBlock.of("$T.INSTANCE.toBigDecimal($S, $L, $S, $L)",
                    CN_COERCIONS, f.name(), raw, d.pattern(), lc);
        }
        return raw;
    }

    private CodeBlock nsLiteral(String ns) {
        if (ns == null) return CodeBlock.of("null");
        return CodeBlock.of("$S", ns);
    }

    private CodeBlock nsMatchExprVar(String ns, String var) {
        if (ns == null) return CodeBlock.of("($L == null || c.getIgnoreNamespace())", var);
        return CodeBlock.of("($S.equals($L) || c.getIgnoreNamespace())", ns, var);
    }

    /** Per-emitter trie node (separate from Classifier's: fewer constraints). */
    private static final class TrieNode {
        final Map<Model.EdgeKey, TrieNode> children = new LinkedHashMap<>();
        final List<AttrEntry> attrEntries = new ArrayList<>();
        final List<Model.FieldSpec> textEntries = new ArrayList<>();
        final List<Model.FieldSpec> nestedEntries = new ArrayList<>();
    }

    private record AttrEntry(String ns, String name, Model.FieldSpec field) {}

    private void insertIntoTrie(TrieNode root, List<Model.PathSeg> segments, Model.FieldSpec f) {
        TrieNode node = root;
        int i = 0;
        for (; i < segments.size(); i++) {
            if (!(segments.get(i) instanceof Model.PathSeg.Element e)) break;
            Model.EdgeKey edge = new Model.EdgeKey(new Model.QKey(e.ns(), e.name()), e.brackets());
            node = node.children.computeIfAbsent(edge, k -> new TrieNode());
        }
        if (i == segments.size()) {
            if (f.coerce() instanceof Model.Coerce.Nested) node.nestedEntries.add(f);
            else node.textEntries.add(f);
        } else if (i == segments.size() - 1 && segments.get(i) instanceof Model.PathSeg.AttrLeaf al) {
            node.attrEntries.add(new AttrEntry(al.ns(), al.name(), f));
        }
    }

    /** Group children of one trie node by base QKey, collecting bracket-list variants in declared order. */
    private LinkedHashMap<Model.QKey, List<Map.Entry<List<Predicate>, TrieNode>>> groupChildrenByQKey(TrieNode node) {
        LinkedHashMap<Model.QKey, List<Map.Entry<List<Predicate>, TrieNode>>> grouped = new LinkedHashMap<>();
        for (var entry : node.children.entrySet()) {
            Model.EdgeKey edge = entry.getKey();
            grouped.computeIfAbsent(edge.qkey(), k -> new ArrayList<>())
                    .add(new java.util.AbstractMap.SimpleEntry<>(edge.brackets(), entry.getValue()));
        }
        return grouped;
    }

    /** Slot identity: counter is keyed by (qname, prefix-of-first-Index-bracket). */
    private record PrefixKey(Model.QKey qkey, List<Predicate> prefix) {}

    private static boolean containsIndex(Predicate p) {
        if (p instanceof Predicate.Index) return true;
        if (p instanceof Predicate.AttrEq) return false;
        if (p instanceof Predicate.And and) return containsIndex(and.getL()) || containsIndex(and.getR());
        if (p instanceof Predicate.Or or) return containsIndex(or.getL()) || containsIndex(or.getR());
        return false;
    }

    private static boolean bracketsHaveIndex(List<Predicate> brackets) {
        for (Predicate b : brackets) if (containsIndex(b)) return true;
        return false;
    }

    /** Brackets up to (but not including) the first Index-bearing bracket. */
    private static List<Predicate> prefixOfFirstIndex(List<Predicate> brackets) {
        List<Predicate> out = new ArrayList<>();
        for (Predicate b : brackets) {
            if (containsIndex(b)) break;
            out.add(b);
        }
        return Collections.unmodifiableList(out);
    }

    /**
     * Walks {@code p} left-to-right and returns the first Index value encountered. The grammar
     * permits {@code [2 and @x='y']} which yields {@code And(Index(2), AttrEq(...))} — Index can
     * appear anywhere.
     */
    private static int firstIndexValue(Predicate p) {
        if (p instanceof Predicate.Index idx) return idx.getN();
        if (p instanceof Predicate.And and) {
            return containsIndex(and.getL()) ? firstIndexValue(and.getL()) : firstIndexValue(and.getR());
        }
        if (p instanceof Predicate.Or) {
            throw new IllegalStateException("Index inside Or predicate is not supported (predicate=" + p + ")");
        }
        throw new IllegalStateException("firstIndexValue: predicate has no Index (" + p + ")");
    }

    /**
     * Returns {@code p} with all Index sub-predicates removed, or {@code null} if removal leaves
     * nothing. Only defined for And-shaped composites — Or with embedded Index is rejected.
     */
    private static Predicate stripIndex(Predicate p) {
        if (p instanceof Predicate.Index) return null;
        if (p instanceof Predicate.AttrEq) return p;
        if (p instanceof Predicate.And and) {
            Predicate l = stripIndex(and.getL());
            Predicate r = stripIndex(and.getR());
            if (l == null) return r;
            if (r == null) return l;
            return new Predicate.And(l, r);
        }
        if (p instanceof Predicate.Or) {
            throw new IllegalStateException("Index inside Or predicate is not supported (predicate=" + p + ")");
        }
        return p;
    }

    private static String slotName(Model.QKey qkey, int ordinal) {
        String safe = qkey.local().replaceAll("[^A-Za-z0-9_]", "_");
        return safe + "_" + ordinal;
    }

    /**
     * Emits {@code int[] __cnt_<slot> = new int[]{0};} declarations for each {@code (qkey, prefix)}
     * slot needed by direct edges in {@code grouped} that contain a positional predicate. Returns
     * a map from {@link PrefixKey} to the slot variable name so call sites can reference
     * {@code __cnt_<name>}/{@code __pre_<name>}/{@code __pos_<name>}.
     */
    private Map<PrefixKey, String> declareCounterSlots(
            CodeBlock.Builder cb,
            Map<Model.QKey, List<Map.Entry<List<Predicate>, TrieNode>>> grouped) {
        LinkedHashMap<PrefixKey, String> slots = new LinkedHashMap<>();
        for (var qe : grouped.entrySet()) {
            Model.QKey qk = qe.getKey();
            for (var be : qe.getValue()) {
                List<Predicate> brackets = be.getKey();
                if (!bracketsHaveIndex(brackets)) continue;
                List<Predicate> prefix = prefixOfFirstIndex(brackets);
                PrefixKey key = new PrefixKey(qk, prefix);
                if (slots.containsKey(key)) continue;
                String name = slotName(qk, slots.size());
                slots.put(key, name);
                cb.addStatement("final int[] __cnt_$L = new int[]{0}", name);
            }
        }
        return slots;
    }

    /**
     * Two-pass dispatch when predicate variants overlap on the same element:
     *  1. attr-only reads run for EVERY matching predicate (childAttr is a pure lookup, no
     *     element consumption). Without this, paths like
     *       link[@type='epub']/@href
     *       link[@type='epub'][@rel='acq']/@href
     *     would race and only the first matching arm would fire.
     *  2. Body-consuming variants (text / nested / descend) dispatch first-match-wins —
     *     a single element body can only be consumed once.
     */
    private void emitPredicateBranches(CodeBlock.Builder cb,
                                       Model.QKey qkey,
                                       List<Map.Entry<List<Predicate>, TrieNode>> branches,
                                       Map<PrefixKey, String> slots,
                                       Model.NestedRegistry registry,
                                       Map<String, ConverterRef> converterRefs) {
        // Per-element pre-compute: increment any counters that key on this qname BEFORE the
        // two-pass dispatch. Each element produces exactly one increment per slot, regardless of
        // how many attr-only / body branches reference that slot.
        for (var slotEntry : slots.entrySet()) {
            PrefixKey key = slotEntry.getKey();
            if (!key.qkey().equals(qkey)) continue;
            String name = slotEntry.getValue();
            if (key.prefix().isEmpty()) {
                // No prefix guard — unconditionally increment.
                cb.addStatement("final int __pos_$L = ++__cnt_$L[0]", name, name);
            } else {
                Predicate folded = key.prefix().get(0);
                for (int i = 1; i < key.prefix().size(); i++) {
                    folded = new Predicate.And(folded, key.prefix().get(i));
                }
                CodeBlock preExpr = plainPredicateExpr(folded);
                cb.addStatement("final boolean __pre_$L = $L", name, preExpr);
                cb.addStatement("final int __pos_$L = __pre_$L ? ++__cnt_$L[0] : 0", name, name, name);
            }
        }

        if (branches.size() == 1 && branches.get(0).getKey().isEmpty()) {
            emitChildBody(cb, branches.get(0).getValue(), registry, converterRefs);
            return;
        }
        for (var entry : branches) {
            TrieNode child = entry.getValue();
            if (child.attrEntries.isEmpty()) continue;
            List<Predicate> brackets = entry.getKey();
            CodeBlock cond = predicateExpr(brackets, qkey, slots);
            cb.add("if ($L) {\n", cond).indent();
            emitAttrEntries(cb, child);
            cb.unindent().add("}\n");
        }
        List<Map.Entry<List<Predicate>, TrieNode>> bodyBranches = new ArrayList<>();
        for (var entry : branches) {
            if (nodeHasBodyContent(entry.getValue())) bodyBranches.add(entry);
        }
        if (bodyBranches.isEmpty()) {
            cb.addStatement("c.skipChild()");
            return;
        }
        boolean first = true;
        for (var entry : bodyBranches) {
            List<Predicate> brackets = entry.getKey();
            String prefix = first ? "if " : "else if ";
            first = false;
            CodeBlock cond = predicateExpr(brackets, qkey, slots);
            cb.add("$L($L) {\n", prefix, cond).indent();
            emitChildBodyContent(cb, entry.getValue(), registry, converterRefs);
            cb.unindent().add("}\n");
        }
        cb.add("else {\n").indent();
        cb.addStatement("c.skipChild()");
        cb.unindent().add("}\n");
    }

    private static boolean nodeHasBodyContent(TrieNode node) {
        return !node.textEntries.isEmpty() || !node.nestedEntries.isEmpty() || !node.children.isEmpty();
    }

    /**
     * Emit a boolean expression for {@code brackets} in the context of {@code qkey}, optionally
     * referencing counter slots from {@code slots}. When any bracket contains a positional
     * {@link Predicate.Index}, the corresponding {@code __pre_<slot>}/{@code __pos_<slot>}
     * references are emitted; everything before the first Index becomes part of the slot's
     * prefix expression and everything after is appended as plain expressions.
     */
    private CodeBlock predicateExpr(List<Predicate> brackets, Model.QKey qkey, Map<PrefixKey, String> slots) {
        if (brackets.isEmpty()) return CodeBlock.of("true");
        if (!bracketsHaveIndex(brackets)) {
            Predicate folded = brackets.get(0);
            for (int i = 1; i < brackets.size(); i++) folded = new Predicate.And(folded, brackets.get(i));
            return plainPredicateExpr(folded);
        }
        int firstIdxIndex = -1;
        for (int i = 0; i < brackets.size(); i++) {
            if (containsIndex(brackets.get(i))) { firstIdxIndex = i; break; }
        }
        if (firstIdxIndex < 0) {
            throw new IllegalStateException("predicateExpr called with no Index in brackets — bug in bracketsHaveIndex");
        }
        List<Predicate> prefix = brackets.subList(0, firstIdxIndex);
        Predicate firstIdxBracket = brackets.get(firstIdxIndex);
        List<Predicate> suffix = brackets.subList(firstIdxIndex + 1, brackets.size());
        int n = firstIndexValue(firstIdxBracket);
        PrefixKey slotKey = new PrefixKey(qkey, prefixOfFirstIndex(brackets));
        String slotName = slots.get(slotKey);
        if (slotName == null) {
            throw new IllegalStateException("missing counter slot for " + slotKey + " at qkey=" + qkey
                    + " — bug in counter detection");
        }
        List<CodeBlock> parts = new ArrayList<>();
        // When the prefix is empty there is no __pre_ variable — the counter is always incremented.
        if (!prefix.isEmpty()) parts.add(CodeBlock.of("__pre_$L", slotName));
        parts.add(CodeBlock.of("(__pos_$L == $L)", slotName, n));
        // If the first-index bracket also contains non-Index predicates (e.g. `[2 and @x='y']`),
        // emit those alongside the position check.
        Predicate residual = stripIndex(firstIdxBracket);
        if (residual != null) parts.add(plainPredicateExpr(residual));
        // Suffix: every bracket after the one that introduced the Index. These are evaluated as
        // ordinary attribute predicates against the current element — they refine the position
        // match but do not affect counter incrementing.
        for (Predicate s : suffix) parts.add(plainPredicateExpr(s));
        CodeBlock acc = parts.get(0);
        for (int i = 1; i < parts.size(); i++) acc = CodeBlock.of("($L && $L)", acc, parts.get(i));
        return acc;
    }

    /**
     * Emit a boolean expression for an Index-free predicate. Equivalent to the legacy
     * {@code predicateExpr} minus the Index arm; descending into And/Or recurses through this same
     * function. Callers must guarantee {@code p} contains no {@link Predicate.Index}.
     */
    private CodeBlock plainPredicateExpr(Predicate p) {
        if (p instanceof Predicate.AttrEq ae) {
            String ns = ae.getName().getNs();
            CodeBlock nsLit = ns == null ? CodeBlock.of("null") : CodeBlock.of("$S", ns);
            String local = ae.getName().getLocal();
            String value = ae.getValue();
            if (ae.getNegate()) {
                // Mirror PathMatcher: missing attr satisfies !=, present-and-different also satisfies.
                return CodeBlock.of("(c.childAttr($L, $S) == null || !$S.equals(c.childAttr($L, $S)))",
                        nsLit, local, value, nsLit, local);
            }
            return CodeBlock.of("($S.equals(c.childAttr($L, $S)))", value, nsLit, local);
        }
        if (p instanceof Predicate.And and) {
            return CodeBlock.of("($L && $L)", plainPredicateExpr(and.getL()), plainPredicateExpr(and.getR()));
        }
        if (p instanceof Predicate.Or or) {
            return CodeBlock.of("($L || $L)", plainPredicateExpr(or.getL()), plainPredicateExpr(or.getR()));
        }
        if (p instanceof Predicate.Index) {
            throw new IllegalStateException("plainPredicateExpr called on Index — counter logic should have stripped this");
        }
        throw new IllegalStateException("unknown predicate: " + p);
    }
}
